// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
//! `define_id7!` / `define_id15!` / `define_id31!` / `define_id63!`:
//! consumer-facing id-type generators with full proof obligations.
//!
//! Each invocation stamps out a `#[repr(transparent)]` newtype over its
//! backing integer with the MSB reserved as the stolen tag bit, implementing:
//!
//!   - the verified `Tagged` (MSB niche, real `bit_vector` extensionality),
//!   - the verified `IndexLike` (identity `as_nat`, type-invariant bound),
//!   - the verified `DenseId` (`Index` = backing int, `is_bit_stealing`),
//!
//! — the exact proof structure of the hand-written [`DenseId31`]
//! (`dense_id.rs`), parameterized by width. The crate verifies one WITNESS
//! instantiation per width (`id_witnesses` module below) in the regular
//! sweep; consumer invocations expand to textually identical code modulo
//! name/prefix (trust ledger group E: macro-expansion-in-unverified-crate,
//! exercised by the canary and runtime proptests).
//!
//! Production-surface items generated OUTSIDE `verus!{}` (plain Rust,
//! contract-free convenience: Debug/Display with prefix, MSB-masking
//! PartialEq/Eq/Ord/Hash, From/TryFrom, `raw()`/`new()`): these mirror
//! production's `define_id_impl!` verbatim. The MSB-masking comparisons are
//! observably identity on clean ids (the type invariant keeps the MSB clear;
//! masking a clear bit is a no-op), so the verified ordering facts
//! (`lemma_order_is_as_nat`) speak for these too.
//!
//! The plain crate retains its historical `Stored` companion symbol, but no
//! portable storage type is generated under that name: here the identifier
//! names the hidden implementation module. Both crates use the backing integer
//! itself as `Tagged::Repr` (as `DenseId31` does). Code intended to compile
//! against either crate uses `<Foo as Tagged>::Repr`, never `StoredFoo`.

/// One past the largest clean 7-bit id.
pub const DENSE7_BOUND: u8 = 0x80;
/// One past the largest clean 15-bit id.
pub const DENSE15_BOUND: u16 = 0x8000;

/// 7-bit id: `u8` backing, bit 7 stolen for the capture tag.
#[macro_export]
macro_rules! define_id7 {
    ($(#[$meta:meta])* $vis:vis struct $Name:ident / $Stored:ident, $prefix:expr;) => {
        $crate::define_id_impl!(@impl $(#[$meta])* $vis, $Name, $Stored, $prefix,
            u8, 0x7Fu8, 0x80u8, 0x80usize);
    };
}

/// 15-bit id: `u16` backing, bit 15 stolen for the capture tag.
#[macro_export]
macro_rules! define_id15 {
    ($(#[$meta:meta])* $vis:vis struct $Name:ident / $Stored:ident, $prefix:expr;) => {
        $crate::define_id_impl!(@impl $(#[$meta])* $vis, $Name, $Stored, $prefix,
            u16, 0x7FFFu16, 0x8000u16, 0x8000usize);
    };
}

/// 31-bit id: `u32` backing, bit 31 stolen for the capture tag.
#[macro_export]
macro_rules! define_id31 {
    ($(#[$meta:meta])* $vis:vis struct $Name:ident / $Stored:ident, $prefix:expr;) => {
        $crate::define_id_impl!(@impl $(#[$meta])* $vis, $Name, $Stored, $prefix,
            u32, 0x7FFF_FFFFu32, 0x8000_0000u32, 0x8000_0000usize);
    };
}

/// 63-bit id: `u64` backing, bit 63 stolen for the capture tag.
#[macro_export]
macro_rules! define_id63 {
    ($(#[$meta:meta])* $vis:vis struct $Name:ident / $Stored:ident, $prefix:expr;) => {
        $crate::define_id_impl!(@impl $(#[$meta])* $vis, $Name, $Stored, $prefix,
            u64, 0x7FFF_FFFF_FFFF_FFFFu64, 0x8000_0000_0000_0000u64, 0x8000_0000_0000_0000usize);
    };
}

/// The shared expansion. `$Int` backing, `$MASK` = value mask (low bits),
/// `$CAP` = the stolen tag bit (MSB), `$BOUNDUSIZE` = one past the largest
/// clean id as a `usize` literal.
#[doc(hidden)]
#[macro_export]
macro_rules! define_id_impl {
    (@impl $(#[$meta:meta])* $vis:vis, $Name:ident, $Stored:ident, $prefix:expr,
     $Int:ty, $MASK:expr, $CAP:expr, $BOUNDUSIZE:expr) => {

        // Hidden impl module: gives the verus!{} expansion the vstd prelude
        // it needs without polluting the invoker's namespace. Named by the
        // `$Stored` identifier (the legacy companion-symbol slot; the portable
        // Tagged Repr in both crates is the backing integer itself).
        #[allow(non_snake_case)]
        // `*r = *r | CAP` (not `|=`): the exact form the verus set_tag/clear_tag
        // proofs are stated over (bit_vector asserts mention the full assign).
        #[allow(clippy::assign_op_pattern)]
        #[doc(hidden)]
        $vis mod $Stored {
            use ::vstd::prelude::*;

            verus! {

        $(#[$meta])*
        /// A clean dense id (generated by `define_id*!`): backing integer with
        /// the MSB always clear (type invariant), naming a value in
        /// `[0, id_bound)`. The stolen MSB is available to `Tagged` consumers.
        #[derive(Copy, Clone)]
        #[repr(transparent)]
        pub struct $Name {
            raw: $Int,
        }

        impl View for $Name {
            type V = nat;

            closed spec fn view(&self) -> nat {
                self.raw as nat
            }
        }

        impl $Name {
            /// Type invariant: a clean id never has the stolen bit set.
            #[verifier::type_invariant]
            spec fn inv(self) -> bool {
                self.raw < $CAP
            }

            /// Construct from a raw integer known to fit below the tag bit.
            /// Production parity: asserts at runtime (a verified caller has
            /// proven the range; an unverified one is trapped before an id
            /// with the tag bit set — violating the type invariant — could
            /// exist).
            #[inline(always)]
            pub fn new(n: $Int) -> (r: $Name)
                ensures n < $CAP ==> r@ == n as nat,
            {
                // Total-with-documented-panic: the range check is the branch.
                if !(n <= $MASK) {
                    $crate::guard::refuse(concat!(stringify!($Name), " exceeds range"));
                }
                $Name { raw: n }
            }

            /// The raw clean value (production parity).
            #[inline(always)]
            pub fn raw(self) -> (r: $Int)
                ensures r as nat == self@,
            {
                proof { use_type_invariant(&self); }
                self.raw
            }

            /// The dense index as a `usize` (for indexing arena vectors).
            #[inline(always)]
            pub fn index(self) -> (r: usize)
                ensures r as nat == self@,
            {
                proof { use_type_invariant(&self); }
                self.raw as usize
            }

            /// Production `DenseId::to_usize` parity (the heavily-used
            /// consumer spelling; same contract as `index`).
            #[inline(always)]
            pub fn to_usize(self) -> (r: usize)
                ensures r as nat == self@,
            {
                proof { use_type_invariant(&self); }
                self.raw as usize
            }
        }

        /// `Default` is id 0 (MSB clear ⟹ type invariant holds). Required by
        /// semi-persistent containers indexing with this id: `restore` fills
        /// reclaimed slots with `Idx::default()` before overwriting them.
        impl ::core::default::Default for $Name {
            fn default() -> (r: $Name)
                ensures r@ == 0,
            {
                $Name { raw: 0 }
            }
        }

        impl $crate::index_like::IndexLike for $Name {
            open spec fn as_nat(self) -> nat { self@ }
            open spec fn max_nat() -> nat { $CAP as nat }
            closed spec fn min_spec() -> Self { $Name { raw: 0 } }
            closed spec fn max_spec() -> Self { $Name { raw: $MASK } }

            proof fn lemma_as_nat_bounded(tracked self) {
                use_type_invariant(self);
            }

            proof fn lemma_as_nat_injective(a: Self, b: Self) {}
            proof fn lemma_min_as_nat() {}
            proof fn lemma_max_as_nat() {}
            proof fn lemma_max_nat_positive() {}
            proof fn lemma_order_is_as_nat(a: Self, b: Self) {}

            // `$CAP` is a `$Int` value and `$Int` is never wider than a pointer here
            // (the macro is instantiated at u8/u32/u64), so the cap is below
            // `usize::MAX + 1` once `usize` is known to be 64 bits wide.
            proof fn lemma_max_nat_fits_usize() {
                $crate::index_like::lemma_u64_usize_64bit();
            }

            fn min() -> Self { $Name { raw: 0 } }
            fn max() -> Self { $Name { raw: $MASK } }

            #[inline(always)]
            fn as_usize(self) -> (r: usize) {
                proof { use_type_invariant(&self); }
                self.raw as usize
            }

            fn try_from_usize(n: usize) -> (r: Option<Self>) {
                if n < $BOUNDUSIZE {
                    Some($Name { raw: n as $Int })
                } else {
                    None
                }
            }

            #[inline(always)]
            fn lt(self, other: Self) -> bool { self.raw < other.raw }
            #[inline(always)]
            fn le(self, other: Self) -> bool { self.raw <= other.raw }
        }

        impl $crate::opt::DenseId for $Name {
            type Index = $Int;

            open spec fn id_nat(self) -> nat { self@ }
            open spec fn id_bound() -> nat { $CAP as nat }

            #[inline(always)]
            fn to_index(self) -> (w: $Int) {
                proof { use_type_invariant(&self); }
                self.raw
            }

            // `as_usize` is inherited from the `IndexLike` supertrait (prod-parity).

            #[inline(always)]
            fn from_usize(n: usize) -> (r: Self) {
                // Match the plain crate: reject before narrowing so an
                // out-of-range position cannot alias an existing ID.
                if n < $BOUNDUSIZE {
                    $Name { raw: n as $Int }
                } else {
                    $crate::guard::refuse(concat!(stringify!($Name), " exceeds range"));
                }
            }

            #[inline(always)]
            fn try_new(n: usize) -> (r: Option<Self>) {
                if n < $BOUNDUSIZE {
                    Some($Name { raw: n as $Int })
                } else {
                    None
                }
            }

            proof fn lemma_id_injective(a: Self, b: Self) {}

            proof fn lemma_as_nat_is_id_nat(self) {}  // both are `self@`

            proof fn lemma_id_nat_bounded(tracked self) {
                use_type_invariant(&self);
            }

            proof fn lemma_id_bound_fits_usize() {
                // $CAP is 2^(w-1) for a word width w <= 64, and
                // usize::MAX + 1 == 2^64 on the pinned 64-bit target.
                $crate::index_like::lemma_u64_usize_64bit();
            }

            open spec fn is_bit_stealing() -> bool { true }

            fn bit_stealing() -> (b: bool) { true }

            proof fn lemma_id_bound_word_relation() {}
        }

        impl $crate::tagged::Tagged for $Name {
            type Repr = $Int;

            closed spec fn value_of(r: $Int) -> $Name {
                $Name { raw: (r & $MASK) }
            }

            open spec fn tag_of(r: $Int) -> bool {
                (r & $CAP) != 0
            }

            open spec fn repr_wf(_r: $Int) -> bool {
                true
            }

            proof fn lemma_repr_extensional(r1: $Int, r2: $Int) {
                // Equal views give equal masked-low-bits; equal tags give
                // equal MSBs; together all bits agree.
                $Name::lemma_value_of_raw(r1);
                $Name::lemma_value_of_raw(r2);
                assert((r1 & $MASK) == (r2 & $MASK));
                assert(((r1 & $CAP) != 0) == ((r2 & $CAP) != 0));
                assert(
                    (r1 & $MASK) == (r2 & $MASK)
                        && (((r1 & $CAP) != 0) == ((r2 & $CAP) != 0))
                        ==> r1 == r2
                ) by (bit_vector);
            }

            fn into_repr(self) -> (r: $Int) {
                proof { use_type_invariant(&self); }
                let x = self.raw;
                assert(x < $CAP ==> (x & $MASK) == x && (x & $CAP) == 0)
                    by (bit_vector);
                proof { $Name::lemma_value_of_raw(self.raw); }
                self.raw
            }

            fn from_repr(r: &$Int) -> (v: $Name) {
                assert(((*r) & $MASK) < $CAP) by (bit_vector);
                proof { $Name::lemma_value_of_raw(*r); }
                $Name { raw: *r & $MASK }
            }

            fn tag(r: &$Int) -> (b: bool) {
                (*r & $CAP) != 0
            }

            fn set_tag(r: &mut $Int) {
                assert(forall|x: $Int|
                    #![auto]
                    ((x | $CAP) & $MASK) == (x & $MASK)
                        && ((x | $CAP) & $CAP) != 0) by (bit_vector);
                *r = *r | $CAP;
            }

            fn clear_tag(r: &mut $Int) {
                assert(forall|x: $Int|
                    #![auto]
                    ((x & $MASK) & $MASK) == (x & $MASK)
                        && ((x & $MASK) & $CAP) == 0) by (bit_vector);
                *r = *r & $MASK;
            }
        }

        impl $Name {
            /// The view of `value_of(r)` is the masked raw (a `bit_vector`
            /// bridge used by the Tagged proofs; the DenseId31 template's
            /// `lemma_value_of_view`, per-type since `value_of` is closed).
            proof fn lemma_value_of_raw(r: $Int)
                ensures
                    <$Name as $crate::tagged::Tagged>::value_of(r)@
                        == (r & $MASK) as nat,
                    (r & $MASK) < $CAP,
            {
                assert((r & $MASK) < $CAP) by (bit_vector);
            }
        }

        } // verus!

        // ------------------------------------------------------------------
        // Production-surface convenience impls (plain Rust, outside verus!):
        // MSB-masking comparisons (identity on clean ids — the type invariant
        // keeps the MSB clear), prefix Debug/Display, integer conversions.
        // ------------------------------------------------------------------

        impl $Name {
            /// Largest storable raw payload (production surface).
            pub const MAX_RAW: $Int = $MASK;

            /// Test-only constructor bypassing the range check (production
            /// surface; `cfg(test)` on both sides).
            #[cfg(test)]
            #[allow(dead_code)]
            pub fn from_raw_unchecked(raw: $Int) -> Self {
                $Name { raw }
            }
        }

        impl PartialEq for $Name {
            #[inline(always)]
            fn eq(&self, other: &Self) -> bool {
                (self.raw() & $MASK) == (other.raw() & $MASK)
            }
        }
        impl Eq for $Name {}

        impl PartialOrd for $Name {
            #[inline(always)]
            fn partial_cmp(&self, other: &Self) -> Option<core::cmp::Ordering> {
                Some(self.cmp(other))
            }
        }
        impl Ord for $Name {
            #[inline(always)]
            fn cmp(&self, other: &Self) -> core::cmp::Ordering {
                (self.raw() & $MASK).cmp(&(other.raw() & $MASK))
            }
        }

        impl core::hash::Hash for $Name {
            #[inline(always)]
            fn hash<H: core::hash::Hasher>(&self, state: &mut H) {
                (self.raw() & $MASK).hash(state);
            }
        }

        impl From<$Name> for $Int {
            #[inline(always)]
            fn from(id: $Name) -> $Int {
                id.raw()
            }
        }

        impl TryFrom<$Int> for $Name {
            type Error = $crate::id_factory::IdRangeError;
            #[inline]
            fn try_from(raw: $Int) -> Result<Self, Self::Error> {
                if raw <= $MASK {
                    Ok(Self::new(raw))
                } else {
                    Err($crate::id_factory::IdRangeError { type_name: stringify!($Name) })
                }
            }
        }

        impl ::core::fmt::Debug for $Name {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                write!(f, "{}{}", $prefix, self.raw())
            }
        }

        impl ::core::fmt::Display for $Name {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                write!(f, "{}{}", $prefix, self.raw())
            }
        }

        } // mod $Stored

        $vis use $Stored::$Name;
    };
}

/// Witness instantiations: one per width, verified in the regular sweep.
/// A consumer's `define_id31!(FooId, ...)` expands to code
/// textually identical to `WitnessId31`'s modulo name/prefix, so these are
/// the proof that every macro-generated id discharges its obligations.
pub mod id_witnesses {
    define_id7! { pub struct WitnessId7 / StoredWitnessId7, "w7_"; }
    define_id15! { pub struct WitnessId15 / StoredWitnessId15, "w15_"; }
    define_id31! { pub struct WitnessId31 / StoredWitnessId31, "w31_"; }
    define_id63! { pub struct WitnessId63 / StoredWitnessId63, "w63_"; }
}

/// Concrete ids production exported from `containers::id` (consumed by the
/// egraph's classes/use-lists).
pub mod ids {
    define_id31! { pub struct SparseSetId / StoredSparseSetId, "s"; }
    define_id31! { pub struct UseListId / StoredUseListId, "ul"; }
    define_id31! { pub struct UseNodeId / StoredUseNodeId, "un"; }
}
