#!/usr/bin/env python3
"""Generate the E6 semi-persistence micro-benchmark programs.

Three program families per base size, in both surface syntaxes:

  sp-t<T>.base.<engine>.egg        base build only (the control whose wall time
                                   is subtracted from the cycles programs)
  sp-t<T>.cycles.<engine>.egg      base + N push/assert/run/check/pop cycles
  sp-t<T>.empty.<engine>.egg       base + N bare push/pop pairs: the state
                                   mechanism on its own, no work inside the scope
  sp-t<T>.norun.<engine>.egg       the same N cycles with the `(run 1)` dropped,
                                   which isolates the state-management cost
  sp-t<T>.rerun.<engine>.egg       base + ONE cycle body, no push/pop: the
                                   per-cycle cost of re-running the prefix, what
                                   a non-persistent engine has to do
  sp-t<T>.rerunnorun.<engine>.egg  the same, for the no-run cycle body

The base is T seeded ground terms `(Mul (Num a) (Add (Num b) (Num c)))` plus two
constant-folding rewrites run to fixpoint. Same seed, same constants, same rules
in both syntaxes: the two engines get byte-for-byte the same problem modulo the
sort-qualification of literal operators (methodology.md section 4).

A cycle asserts ten fresh ground terms, unions one fresh pair and one pair of
*base* e-classes (so restore has base state to undo, not only appended state),
runs one iteration, and checks one folding consequence.

Usage:
    python3 gen-semipersistence.py                  # every size in SIZES
    python3 gen-semipersistence.py --terms 1000     # one size
"""

import argparse
import os
import random

# Base sizes as term counts. Node counts they reach are engine-specific and are
# recorded in the ledger; see semi-persistence.md.
SIZES = [880, 2_650, 8_900, 27_000, 100_000]

# Cycle counts per variant. The full cycle is capped at 20 because one round of
# saturation over a million-node base is not cheap on either engine; the two
# cheap variants run 200 so that the measured delta dominates the base build it
# is subtracted from (a 20-cycle delta is ~15% of the base wall at the largest
# size, which is inside this machine's background-load noise).
CYCLES = {"cycles": 20, "empty": 200, "norun": 200, "empty20k": 20_000}
SEED = 20260816

# Constant ranges. Products stay under 1e8 so neither engine's i64 arithmetic
# can overflow, which would be a difference in behaviour rather than in speed.
A_RANGE = (2, 999)
BC_RANGE = (1, 1_000_000_000)

# Fresh constants a cycle asserts live above every base constant, so a cycle's
# terms are new nodes in every run and never collide with the base.
FRESH_BASE = 10_000_000


def base_terms(n_terms):
    rng = random.Random(SEED)
    return [
        (
            rng.randint(*A_RANGE),
            rng.randint(*BC_RANGE),
            rng.randint(*BC_RANGE),
        )
        for _ in range(n_terms)
    ]


def preamble(native, n_terms):
    add = "i64::+" if native else "+"
    mul = "i64::*" if native else "*"
    head = ";; TYPES: machine\n" if native else ""
    return (
        head
        + f""";; E6 semi-persistence micro-benchmark, {n_terms} base terms, seed {SEED}.
;; Generated by gen-semipersistence.py; do not edit by hand.
(datatype Math
  (Num i64)
  (Var String)
  (Add Math Math)
  (Mul Math Math))

(rewrite (Add (Num a) (Num b)) (Num ({add} a b)))
(rewrite (Mul (Num a) (Num b)) (Num ({mul} a b)))
"""
    )


def base_body(terms):
    lines = [f"(Mul (Num {a}) (Add (Num {b}) (Num {c})))" for a, b, c in terms]
    lines.append("(run 10)")
    return "\n".join(lines) + "\n"


def cycle_body(k, terms, native, pushpop, run=True):
    """One cycle. `pushpop` False writes the same work with no push/pop, which is
    what the rerun (non-persistent) variant times. `run` False drops the
    saturation step, which isolates push/pop and assertion cost from the cost of
    the round of matching a cycle also pays."""
    out = []
    if pushpop:
        out.append("(push)")
    f = FRESH_BASE + k * 1000
    # Ten fresh ground terms: five Add, five Mul.
    for i in range(5):
        out.append(f"(Add (Num {f + 2 * i}) (Num {f + 2 * i + 1}))")
    for i in range(5):
        out.append(f"(Mul (Num {f + 100 + 2 * i}) (Num {f + 100 + 2 * i + 1}))")
    # Two unions: one between fresh e-classes, one between two base e-classes so
    # the cycle dirties base state that restore must undo.
    out.append(f'(union (Var "spu{k}a") (Var "spu{k}b"))')
    b0 = terms[k % len(terms)][1]
    b1 = terms[(k + len(terms) // 2) % len(terms)][2]
    out.append(f"(union (Num {b0}) (Num {b1}))")
    if run:
        out.append("(run 1)")
        # A folding consequence of this cycle's own first fresh term.
        out.append(f"(check (= (Add (Num {f}) (Num {f + 1})) (Num {2 * f + 1})))")
    else:
        # Without a run the only new consequence is the union just asserted.
        out.append(f'(check (= (Var "spu{k}a") (Var "spu{k}b")))')
    if pushpop:
        out.append("(pop)")
    return "\n".join(out) + "\n"


def stats_tail(name, native):
    if native:
        return f'(print-size)\n(print-stats :file "{name}.stats.json")\n'
    return (
        "(print-size)\n"
        "(print-stats)\n"
        f'(print-stats :file "{name}.stats.json")\n'
    )


def write(outdir, n_terms, native):
    engine = "native" if native else "egglog"
    terms = base_terms(n_terms)
    pre = preamble(native, n_terms)
    base = base_body(terms)

    variants = {
        "base": "",
        "cycles": "".join(
            cycle_body(k, terms, native, True) for k in range(CYCLES["cycles"])
        ),
        "empty": "".join("(push)\n(pop)\n" for _ in range(CYCLES["empty"])),
        # Opt-in high-resolution twin of `empty`: once a bare pair costs tens of
        # microseconds, a 200-pair delta is a rounding error on the base wall
        # time it is subtracted from, and 20 000 pairs put the delta back above
        # it. Not in the runner's default variant list — 20 000 pairs of a
        # snapshot-copying engine is minutes per run.
        "empty20k": "".join("(push)\n(pop)\n" for _ in range(CYCLES["empty20k"])),
        "norun": "".join(
            cycle_body(k, terms, native, True, run=False)
            for k in range(CYCLES["norun"])
        ),
        "rerun": cycle_body(0, terms, native, False),
        "rerunnorun": cycle_body(0, terms, native, False, run=False),
    }
    for variant, body in variants.items():
        name = f"sp-t{n_terms}.{variant}.{engine}"
        path = os.path.join(outdir, name + ".egg")
        with open(path, "w") as fh:
            fh.write(pre + "\n" + base + "\n" + body + "\n" + stats_tail(name, native))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--terms", type=int, action="append")
    ap.add_argument("--outdir", default=os.path.dirname(os.path.abspath(__file__)))
    args = ap.parse_args()
    for n in args.terms or SIZES:
        write(args.outdir, n, native=False)
        write(args.outdir, n, native=True)
        print(f"wrote sp-t{n}.*")


if __name__ == "__main__":
    main()
