#!/usr/bin/env python3
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Generate the add-ac width-scaling sweep programs.

For sum width n: left term 1+(2+(...+n)) right-nested, goal term the full reversal
n+((n-1)+(...+1)), also right-nested.  Three configurations per n, mirroring the
math-add-ac trio:

    addac-n<k>.egglog.egg   egglog, A/C as its two rewrite rules
    addac-n<k>.rules.egg    ours,   A/C as the same two rewrite rules
    addac-n<k>.native.egg   ours,   A/C on the operator declaration

Usage: python3 gen-addac-sweep.py 7 9 11 13 15
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

BUDGET = 50  # generous :until budget; the metric is time-to-goal, not iterations


def nest(consts, ind):
    """Right-nested (Add c1 (Add c2 (... (Add c_{k-1} c_k)))) over the given literals."""
    if len(consts) == 1:
        return f"{' ' * ind}(Const {consts[0]}.0)"
    head = f"{' ' * ind}(Add (Const {consts[0]}.0)\n"
    return head + nest(consts[1:], ind + 5) + ")"


def terms(n):
    return nest(list(range(1, n + 1)), 0), nest(list(range(n, 0, -1)), 0)


def indent(block, by):
    pad = " " * by
    return "\n".join(pad + line.lstrip() if i == 0 else line
                     for i, line in enumerate(block.splitlines()))


def egglog(n):
    lhs, rhs = terms(n)
    return f""";; add-ac width-scaling sweep, n = {n}.  Generated by gen-addac-sweep.py.
;; Generalises the `add-ac` ruleset block of egglog tests/web-demo/math.egg (7b1adf2,
;; lines 138-160) from its fixed seven-term sum to sum width n, keeping both the
;; right-nested input and the fully reversed goal term of the original block.
;; See addac-sweep.md.

(datatype Math
    (Add Math Math)
    (Const f64))

(ruleset add-ac)
(rewrite (Add a b) (Add b a) :ruleset add-ac)
(rewrite (Add a (Add b c)) (Add (Add a b) c) :ruleset add-ac)
;; Add one through {n}, right-nested
(let $res
{indent(lhs, 2)})
;; The goal term, {n} down to one, bound rather than left inline: our `check` and our
;; `:until` build their terms, egglog's query them, so binding it here is what makes the
;; three programs start from the same e-graph.  See addac-sweep.md.
(let $goal
{indent(rhs, 2)})
(run add-ac {BUDGET} :until (= $res $goal))
(check (= $res $goal))
(print-size)
(print-stats)
(print-stats :file "addac-n{n}.egglog.stats.json")
"""


def rules(n):
    lhs, rhs = terms(n)
    return f""";; TYPES: machine
;; add-ac width-scaling sweep, n = {n}.  Generated by gen-addac-sweep.py.
;; Config: A/C modelled as explicit rewrite rules, egglog's own encoding.
;; Same datatype, same two rules, same budget and same goal as addac-n{n}.egglog.egg.
;; See addac-sweep.md.

(datatype Math
    (Add Math Math)
    (Const f64))

(ruleset add_ac)
(rewrite (Add a b) (Add b a) :ruleset add_ac)
(rewrite (Add a (Add b c)) (Add (Add a b) c) :ruleset add_ac)
;; Add one through {n}, right-nested
(let res
{indent(lhs, 2)})
;; The goal term, {n} down to one.
(let goal
{indent(rhs, 2)})
(run add_ac {BUDGET} :until (= res goal))
(check (= res goal))
(print-size)
(print-stats :file "addac-n{n}.rules.stats.json")
"""


def native(n):
    lhs, rhs = terms(n)
    return f""";; TYPES: machine
;; add-ac width-scaling sweep, n = {n}.  Generated by gen-addac-sweep.py.
;; Config: native AC.  Add is declared variadic :assoc-comm and the two rewrite rules
;; are deleted; the ruleset is kept declared and still run, so the command sequence
;; matches addac-n{n}.rules.egg.  The goal holds at construction, so the run is (run 1)
;; rather than the :until form.  See addac-sweep.md.

(datatype Math
    (Add Math :assoc-comm)
    (Const f64))

(ruleset add_ac)
;; Add one through {n}, right-nested
(let res
{indent(lhs, 2)})
;; The goal term, {n} down to one.  It flattens to the same multiset as res at
;; construction, so the two are already one class before the run.
(let goal
{indent(rhs, 2)})
(run add_ac 1)
(check (= res goal))
(print-size)
(print-stats :file "addac-n{n}.native.stats.json")
"""


def main():
    ns = [int(a) for a in sys.argv[1:]] or [7, 9, 11, 13, 15]
    for n in ns:
        for suffix, body in (("egglog", egglog(n)), ("rules", rules(n)),
                             ("native", native(n))):
            path = os.path.join(HERE, f"addac-n{n}.{suffix}.egg")
            with open(path, "w") as fh:
                fh.write(body)
            print(f"wrote {path}")


if __name__ == "__main__":
    main()
