[package]
name = "semi-persistent"
version = "0.2.0"
edition = "2024"
rust-version = "1.97.1"
license = "Apache-2.0"
description = "Semi-persistent data structures, e-graphs, and recursion schemes"
repository = "https://github.com/yaspar-org/semi-persistent"
homepage = "https://github.com/yaspar-org/semi-persistent"
documentation = "https://docs.rs/semi-persistent"
readme = "../README.md"

[dependencies]
semi-persistent-containers = { package = "semi-persistent-containers-verus", path = "../containers-verus", version = "0.2.0" }
semi-persistent-egraph = { path = "../egraph", version = "0.2.0" }
semi-persistent-traversals = { path = "../traversals", version = "0.2.0" }
