// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
//! Partitioned-arena recursion schemes for mutually recursive type families.
//!
//! Declare a family with `rec_family!`, get per-sort arenas with typed IDs
//! and a full suite of stack-safe, memoized folds, unfolds, transforms,
//! and zippers. See the crate-level [`rec_family!`] macro for usage.

use std::sync::atomic::{AtomicU64, Ordering};

// Allow integration tests and downstream crates to use `::semi_persistent_traversals::` paths
// generated by the proc macro.
extern crate self as semi_persistent_traversals;

pub use rustc_hash::FxBuildHasher;
pub use rustc_hash::FxHashMap;
pub use rustc_hash::FxHashSet;
pub use semi_persistent_traversals_derive::rec_family;

#[doc(hidden)]
pub mod __private {
    pub use smallvec::SmallVec;
}

// ---------------------------------------------------------------------------
// Memo strategy — None (linear scan) vs Vec (dense) vs Map (sparse)
// ---------------------------------------------------------------------------

/// Memoization strategy selector. Controls how traversals allocate their
/// internal tables.
///
/// - [`memo::None`]: No memoization — stack-based traversal without dedup
///   checks. Fastest for trees with no sharing. **Incorrect on DAGs.**
/// - [`memo::Vec`]: O(store_size) allocation, O(1) lookup via array index.
///   Default. Best when the reachable subtree is a large fraction of the
///   store, or when the store is a DAG with sharing.
/// - [`memo::Map`]: O(reachable) allocation, O(1) amortized lookup via hash
///   map. Best when folding a small subtree in a large store.
pub trait MemoStrategy: sealed::Sealed {
    type Memo<V>: MemoOps<V>;
    type Visit: VisitOps;
    type Mapping: MappingOps;
    /// If true, skip memoization checks in fold (stack-based, no dedup).
    const NO_MEMO: bool = false;
}

pub mod memo {
    //! Memoization strategy types.
    //!
    //! ```ignore
    //! use semi_persistent_traversals::memo;
    //! store.with_strategy::<memo::None>().fold(root, alg);  // no memo, stack-based
    //! store.with_strategy::<memo::Vec>().fold(root, alg);   // dense Vec memo
    //! store.with_strategy::<memo::Map>().fold(root, alg);   // sparse hash-map memo
    //! ```

    /// No memoization — stack-based traversal, no dedup. Fastest for trees.
    pub struct None;
    /// Dense memoization — `Vec`-backed tables sized to the full store.
    pub struct Vec;
    /// Sparse memoization — `HashMap`-backed tables sized to reachable nodes.
    pub struct Map;
}

/// Backwards compat aliases.
pub type Dense = memo::Vec;
pub type Sparse = memo::Map;

mod sealed {
    pub trait Sealed {}
    impl Sealed for super::memo::None {}
    impl Sealed for super::memo::Vec {}
    impl Sealed for super::memo::Map {}
}

impl MemoStrategy for memo::None {
    type Memo<V> = DenseMemo<V>;
    type Visit = DenseVisit;
    type Mapping = DenseMapping;
    const NO_MEMO: bool = true;
}

impl MemoStrategy for memo::Vec {
    type Memo<V> = DenseMemo<V>;
    type Visit = DenseVisit;
    type Mapping = DenseMapping;
}

impl MemoStrategy for memo::Map {
    type Memo<V> = SparseMemo<V>;
    type Visit = SparseVisit;
    type Mapping = SparseMapping;
}

// --- MemoOps: Option<V> table ---

pub trait MemoOps<V> {
    fn new(arena_len: usize) -> Self;
    fn get(&self, k: usize) -> Option<&V>;
    fn set(&mut self, k: usize, v: V);
    fn take(&mut self, k: usize) -> Option<V>;
}

pub struct DenseMemo<V>(Vec<Option<V>>);
impl<V> MemoOps<V> for DenseMemo<V> {
    #[inline]
    fn new(len: usize) -> Self {
        Self((0..len).map(|_| None).collect())
    }
    #[inline(always)]
    fn get(&self, k: usize) -> Option<&V> {
        self.0[k].as_ref()
    }
    #[inline(always)]
    fn set(&mut self, k: usize, v: V) {
        self.0[k] = Some(v);
    }
    #[inline]
    fn take(&mut self, k: usize) -> Option<V> {
        self.0[k].take()
    }
}

pub struct SparseMemo<V>(FxHashMap<usize, V>);
impl<V> MemoOps<V> for SparseMemo<V> {
    #[inline]
    fn new(_: usize) -> Self {
        Self(FxHashMap::default())
    }
    #[inline(always)]
    fn get(&self, k: usize) -> Option<&V> {
        self.0.get(&k)
    }
    #[inline(always)]
    fn set(&mut self, k: usize, v: V) {
        self.0.insert(k, v);
    }
    #[inline]
    fn take(&mut self, k: usize) -> Option<V> {
        self.0.remove(&k)
    }
}

// --- VisitOps: bool set ---

pub trait VisitOps {
    fn new(arena_len: usize) -> Self;
    fn visited(&self, k: usize) -> bool;
    fn mark(&mut self, k: usize);
}

pub struct DenseVisit(Vec<bool>);
impl VisitOps for DenseVisit {
    #[inline]
    fn new(len: usize) -> Self {
        Self(vec![false; len])
    }
    #[inline(always)]
    fn visited(&self, k: usize) -> bool {
        self.0[k]
    }
    #[inline(always)]
    fn mark(&mut self, k: usize) {
        self.0[k] = true;
    }
}

pub struct SparseVisit(FxHashSet<usize>);
impl VisitOps for SparseVisit {
    #[inline]
    fn new(_: usize) -> Self {
        Self(FxHashSet::default())
    }
    #[inline(always)]
    fn visited(&self, k: usize) -> bool {
        self.0.contains(&k)
    }
    #[inline(always)]
    fn mark(&mut self, k: usize) {
        self.0.insert(k);
    }
}

// --- MappingOps: usize → usize table ---

pub trait MappingOps {
    fn new(arena_len: usize) -> Self;
    fn get(&self, k: usize) -> usize;
    fn set(&mut self, k: usize, v: usize);
}

pub struct DenseMapping(Vec<usize>);
impl MappingOps for DenseMapping {
    #[inline]
    fn new(len: usize) -> Self {
        Self(vec![0; len])
    }
    #[inline(always)]
    fn get(&self, k: usize) -> usize {
        self.0[k]
    }
    #[inline(always)]
    fn set(&mut self, k: usize, v: usize) {
        self.0[k] = v;
    }
}

pub struct SparseMapping(FxHashMap<usize, usize>);
impl MappingOps for SparseMapping {
    #[inline]
    fn new(_: usize) -> Self {
        Self(FxHashMap::default())
    }
    #[inline(always)]
    fn get(&self, k: usize) -> usize {
        self.0[&k]
    }
    #[inline(always)]
    fn set(&mut self, k: usize, v: usize) {
        self.0.insert(k, v);
    }
}

// ---------------------------------------------------------------------------
// Variadic — pool-backed variable-length child list
// ---------------------------------------------------------------------------

static NEXT_VARIADIC_POOL_ID: AtomicU64 = AtomicU64::new(1);

#[doc(hidden)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct VariadicPoolId(u64);

#[doc(hidden)]
pub struct VariadicPool<R> {
    id: VariadicPoolId,
    entries: Vec<R>,
}

impl<R> VariadicPool<R> {
    #[doc(hidden)]
    pub fn new() -> Self {
        let id = NEXT_VARIADIC_POOL_ID
            .fetch_update(Ordering::Relaxed, Ordering::Relaxed, |id| id.checked_add(1))
            .expect("variadic pool identity space exhausted");
        Self {
            id: VariadicPoolId(id),
            entries: Vec::new(),
        }
    }

    #[doc(hidden)]
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    #[doc(hidden)]
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    #[doc(hidden)]
    pub fn truncate(&mut self, len: usize) {
        self.entries.truncate(len);
    }
}

impl<R: Clone> VariadicPool<R> {
    #[doc(hidden)]
    pub fn alloc(&mut self, children: &[R]) -> Variadic<R> {
        let start = self.entries.len();
        self.entries.extend_from_slice(children);
        Variadic::Span {
            pool: self.id,
            start,
            len: children.len(),
        }
    }

    #[doc(hidden)]
    pub fn clone_rebranded(&self) -> Self {
        let mut cloned = Self::new();
        cloned.entries.clone_from(&self.entries);
        cloned
    }
}

#[derive(Clone, Debug)]
pub enum Variadic<R> {
    /// `usize` offsets, not an id-family word: the pool a span indexes holds
    /// CONCATENATED child lists, so its population is the sum of arities —
    /// bounded by memory, not by any id capacity (2^31 nodes of 2^31 children
    /// is 2^62 entries). A `u32` here capped every pool at 2^32 entries
    /// (~16 GiB at 4-byte ids — reachable), and a wrapped offset is a valid
    /// offset into someone else's span. The width is free: the `Resolved`
    /// variant's inline `SmallVec` dominates the enum's size either way.
    Span {
        pool: VariadicPoolId,
        start: usize,
        len: usize,
    },
    Resolved(smallvec::SmallVec<[R; 4]>),
}

impl<R> Variadic<R> {
    /// Borrow the children represented by this value.
    ///
    /// `pool` must be the typed pool belonging to the node's owning store.
    /// It is ignored for an inline [`Variadic::Resolved`] value.
    #[inline]
    pub fn as_slice<'a>(&'a self, pool: &'a VariadicPool<R>) -> &'a [R] {
        match self {
            Variadic::Resolved(v) => v.as_slice(),
            Variadic::Span {
                pool: owner,
                start,
                len,
            } => {
                assert_eq!(*owner, pool.id, "variadic span belongs to a different pool");
                let end = start
                    .checked_add(*len)
                    .filter(|end| *end <= pool.entries.len())
                    .expect("variadic span is outside its owning pool");
                &pool.entries[*start..end]
            }
        }
    }

    #[doc(hidden)]
    pub fn rebrand(&self, old: &VariadicPool<R>, new: &VariadicPool<R>) -> Self
    where
        R: Clone,
    {
        match self {
            Variadic::Resolved(values) => Variadic::Resolved(values.clone()),
            Variadic::Span { pool, start, len } => {
                assert_eq!(*pool, old.id, "variadic span belongs to a different pool");
                assert!(
                    start
                        .checked_add(*len)
                        .is_some_and(|end| end <= old.entries.len()),
                    "variadic span is outside its owning pool"
                );
                Variadic::Span {
                    pool: new.id,
                    start: *start,
                    len: *len,
                }
            }
        }
    }

    #[doc(hidden)]
    pub fn into_pooled(self, pool: &mut VariadicPool<R>) -> Self
    where
        R: Clone,
    {
        match self {
            Variadic::Resolved(values) => pool.alloc(values.as_slice()),
            span @ Variadic::Span { .. } => {
                let _ = span.as_slice(pool);
                span
            }
        }
    }

    /// Iterate an inline, traversal-produced value.
    ///
    /// Pool-backed values need their owning store and must be accessed with
    /// [`Variadic::as_slice`]. Generated traversals perform that resolution
    /// automatically before invoking user code.
    pub fn iter(&self) -> std::slice::Iter<'_, R> {
        match self {
            Variadic::Resolved(v) => v.iter(),
            Variadic::Span { .. } => {
                panic!("pool-backed Variadic requires its owning store")
            }
        }
    }
    pub fn len(&self) -> usize {
        match self {
            Variadic::Resolved(v) => v.len(),
            Variadic::Span { len, .. } => *len,
        }
    }
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
    pub fn map_all<S>(self, f: &mut impl FnMut(R) -> S) -> Variadic<S> {
        match self {
            Variadic::Resolved(v) => Variadic::Resolved(v.into_iter().map(f).collect()),
            _ => panic!("unresolved"),
        }
    }
    pub fn into_vec(self) -> Vec<R> {
        match self {
            Variadic::Resolved(v) => v.into_vec(),
            _ => panic!("unresolved"),
        }
    }
}

impl<R> IntoIterator for Variadic<R> {
    type Item = R;
    type IntoIter = std::vec::IntoIter<R>;
    fn into_iter(self) -> Self::IntoIter {
        self.into_vec().into_iter()
    }
}

impl<R> std::ops::Index<usize> for Variadic<R> {
    type Output = R;
    fn index(&self, i: usize) -> &R {
        match self {
            Variadic::Resolved(v) => &v[i],
            _ => panic!("unresolved"),
        }
    }
}

// A Span cannot compare or hash its children without its owning pool. These
// impls therefore describe the representation; generated store dedup uses
// pool-aware semantic hashing and equality instead.
impl<R: PartialEq> PartialEq for Variadic<R> {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Variadic::Resolved(a), Variadic::Resolved(b)) => a == b,
            (
                Variadic::Span {
                    pool: p1,
                    start: s1,
                    len: l1,
                },
                Variadic::Span {
                    pool: p2,
                    start: s2,
                    len: l2,
                },
            ) => p1 == p2 && s1 == s2 && l1 == l2,
            _ => false,
        }
    }
}
impl<R: Eq> Eq for Variadic<R> {}
impl<R: std::hash::Hash> std::hash::Hash for Variadic<R> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        match self {
            Variadic::Resolved(v) => {
                0u8.hash(state);
                v.hash(state);
            }
            Variadic::Span { pool, start, len } => {
                1u8.hash(state);
                pool.hash(state);
                start.hash(state);
                len.hash(state);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Ann — annotated result for fold_with_history
// ---------------------------------------------------------------------------

/// Annotated result for `fold_with_history`.
///
/// - `value`: the folded result for this node
/// - `children`: untyped arena indices of this node's direct children
///
/// A parent receives this metadata for each direct child, so it can observe
/// one generation of grandchild shape, such as arity or leaf/non-leaf status.
/// The indices do not identify their sort and do not provide access to
/// recursive annotations or the fold's private memo tables.
pub struct Ann<A> {
    pub value: A,
    pub children: smallvec::SmallVec<[usize; 8]>,
}
