// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
//! Arena-based recursion schemes for Rust.
//!
//! Declare a functor (`enum E<R> { Lit(i64), Add(R, R), ... }`), implement
//! `Functor`, and get stack-safe, memoized folds, unfolds, transforms, and
//! more — all without writing a single recursive function.

// Allow integration tests and downstream crates to use `::semi_persistent_traversals::` paths
// generated by the proc macro.
extern crate self as semi_persistent_traversals;

pub use rustc_hash::FxBuildHasher;
pub use rustc_hash::FxHashMap;
pub use rustc_hash::FxHashSet;

/// The hash map type used by Arena and HcArena for deduplication.
/// Change this type alias to swap the hash function globally.
pub type ArenaMap<K, V> = std::collections::HashMap<K, V, FxBuildHasher>;

// ---------------------------------------------------------------------------
// Memo strategy — None (linear scan) vs Vec (dense) vs Map (sparse)
// ---------------------------------------------------------------------------

/// Memoization strategy selector. Implement this trait to control how
/// traversals allocate their internal tables.
///
/// - [`memo::None`]: No memoization — stack-based traversal from root without
///   dedup checks. Fastest for trees with no sharing. Recomputes nodes that
///   are reachable via multiple paths.
/// - [`memo::Vec`]: O(arena) allocation, O(1) lookup via array index. Best
///   when the reachable subtree is a large fraction of the arena, or when
///   the arena is a DAG with sharing.
/// - [`memo::Map`]: O(reachable) allocation, O(1) amortized lookup via hash
///   map. Best when folding a small subtree in a large arena.
pub trait MemoStrategy: sealed::Sealed {
    type Memo<V>: MemoOps<V>;
    type Visit: VisitOps;
    type Mapping: MappingOps;
    /// If true, skip memoization checks in fold/fold_ref (stack-based, no dedup).
    const NO_MEMO: bool = false;
}

pub mod memo {
    //! Memoization strategy types.
    //!
    //! ```ignore
    //! use semi_persistent_traversals::memo;
    //! arena.with_strategy::<memo::None>().fold(root, alg);  // no memo, stack-based
    //! arena.with_strategy::<memo::Vec>().fold(root, alg);   // dense Vec memo
    //! arena.with_strategy::<memo::Map>().fold(root, alg);   // sparse hash-map memo
    //! ```

    /// No memoization — stack-based traversal, no dedup. Fastest for trees.
    pub struct None;
    /// Dense memoization — `Vec`-backed tables sized to the full arena.
    pub struct Vec;
    /// Sparse memoization — `HashMap`-backed tables sized to reachable nodes.
    pub struct Map;
}

/// Backwards compat aliases.
pub type Dense = memo::Vec;
pub type Sparse = memo::Map;

mod sealed {
    pub trait Sealed {}
    impl Sealed for super::memo::None {}
    impl Sealed for super::memo::Vec {}
    impl Sealed for super::memo::Map {}
}

impl MemoStrategy for memo::None {
    type Memo<V> = DenseMemo<V>;
    type Visit = DenseVisit;
    type Mapping = DenseMapping;
    const NO_MEMO: bool = true;
}

impl MemoStrategy for memo::Vec {
    type Memo<V> = DenseMemo<V>;
    type Visit = DenseVisit;
    type Mapping = DenseMapping;
}

impl MemoStrategy for memo::Map {
    type Memo<V> = SparseMemo<V>;
    type Visit = SparseVisit;
    type Mapping = SparseMapping;
}

// --- MemoOps: Option<V> table ---

pub trait MemoOps<V> {
    fn new(arena_len: usize) -> Self;
    fn get(&self, k: usize) -> Option<&V>;
    fn set(&mut self, k: usize, v: V);
    fn take(&mut self, k: usize) -> Option<V>;
}

pub struct DenseMemo<V>(Vec<Option<V>>);
impl<V> MemoOps<V> for DenseMemo<V> {
    #[inline]
    fn new(len: usize) -> Self {
        Self((0..len).map(|_| None).collect())
    }
    #[inline(always)]
    fn get(&self, k: usize) -> Option<&V> {
        self.0[k].as_ref()
    }
    #[inline(always)]
    fn set(&mut self, k: usize, v: V) {
        self.0[k] = Some(v);
    }
    #[inline]
    fn take(&mut self, k: usize) -> Option<V> {
        self.0[k].take()
    }
}

pub struct SparseMemo<V>(FxHashMap<usize, V>);
impl<V> MemoOps<V> for SparseMemo<V> {
    #[inline]
    fn new(_: usize) -> Self {
        Self(FxHashMap::default())
    }
    #[inline(always)]
    fn get(&self, k: usize) -> Option<&V> {
        self.0.get(&k)
    }
    #[inline(always)]
    fn set(&mut self, k: usize, v: V) {
        self.0.insert(k, v);
    }
    #[inline]
    fn take(&mut self, k: usize) -> Option<V> {
        self.0.remove(&k)
    }
}

// --- VisitOps: bool set ---

pub trait VisitOps {
    fn new(arena_len: usize) -> Self;
    fn visited(&self, k: usize) -> bool;
    fn mark(&mut self, k: usize);
}

pub struct DenseVisit(Vec<bool>);
impl VisitOps for DenseVisit {
    #[inline]
    fn new(len: usize) -> Self {
        Self(vec![false; len])
    }
    #[inline(always)]
    fn visited(&self, k: usize) -> bool {
        self.0[k]
    }
    #[inline(always)]
    fn mark(&mut self, k: usize) {
        self.0[k] = true;
    }
}

pub struct SparseVisit(FxHashSet<usize>);
impl VisitOps for SparseVisit {
    #[inline]
    fn new(_: usize) -> Self {
        Self(FxHashSet::default())
    }
    #[inline(always)]
    fn visited(&self, k: usize) -> bool {
        self.0.contains(&k)
    }
    #[inline(always)]
    fn mark(&mut self, k: usize) {
        self.0.insert(k);
    }
}

// --- MappingOps: usize → usize table ---

pub trait MappingOps {
    fn new(arena_len: usize) -> Self;
    fn get(&self, k: usize) -> usize;
    fn set(&mut self, k: usize, v: usize);
}

pub struct DenseMapping(Vec<usize>);
impl MappingOps for DenseMapping {
    #[inline]
    fn new(len: usize) -> Self {
        Self(vec![0; len])
    }
    #[inline(always)]
    fn get(&self, k: usize) -> usize {
        self.0[k]
    }
    #[inline(always)]
    fn set(&mut self, k: usize, v: usize) {
        self.0[k] = v;
    }
}

pub struct SparseMapping(FxHashMap<usize, usize>);
impl MappingOps for SparseMapping {
    #[inline]
    fn new(_: usize) -> Self {
        Self(FxHashMap::default())
    }
    #[inline(always)]
    fn get(&self, k: usize) -> usize {
        self.0[&k]
    }
    #[inline(always)]
    fn set(&mut self, k: usize, v: usize) {
        self.0.insert(k, v);
    }
}

// ---------------------------------------------------------------------------
// Traits
// ---------------------------------------------------------------------------

/// A node functor: one layer parameterized over child type R.
pub trait Functor<R>: Sized {
    type Mapped<S>;
    fn map<S>(self, f: impl FnMut(R) -> S) -> Self::Mapped<S>;
    /// Map by reference — borrows data fields, maps only children. No node clone.
    fn map_ref<S>(&self, mut f: impl FnMut(&R) -> S) -> Self::Mapped<S>
    where
        Self: Clone,
        R: Clone,
    {
        self.clone().map(|r| f(&r))
    }
    /// Collect child values into a caller-provided buffer. Zero alloc for ≤8 children.
    fn children_into(&self, buf: &mut smallvec::SmallVec<[R; 8]>)
    where
        R: Copy,
        Self: Clone,
    {
        buf.clear();
        self.clone().map(|c| {
            buf.push(c);
            c
        });
    }
}

// ---------------------------------------------------------------------------
// Id — typed handle into an arena
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct Id(pub usize);

// ---------------------------------------------------------------------------
// StringId / StringPool — interned strings
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct StringId(pub u32);

#[derive(Clone, Default)]
pub struct StringPool {
    strings: Vec<String>,
    index: FxHashMap<String, u32>,
}

impl StringPool {
    pub fn new() -> Self {
        Self::default()
    }
    pub fn intern(&mut self, s: &str) -> StringId {
        if let Some(&id) = self.index.get(s) {
            return StringId(id);
        }
        let id = self.strings.len() as u32;
        self.index.insert(s.to_owned(), id);
        self.strings.push(s.to_owned());
        StringId(id)
    }
    pub fn get(&self, id: StringId) -> &str {
        &self.strings[id.0 as usize]
    }
}

// ---------------------------------------------------------------------------
// Variadic<R> — pool-backed variable-length child list
// ---------------------------------------------------------------------------

#[derive(Clone, Debug)]
pub enum Variadic<R> {
    Span { start: u32, len: u32 },
    Resolved(smallvec::SmallVec<[R; 4]>),
}

impl<R> Variadic<R> {
    pub fn iter(&self) -> std::slice::Iter<'_, R> {
        match self {
            Variadic::Resolved(v) => v.iter(),
            _ => panic!("unresolved"),
        }
    }
    pub fn len(&self) -> usize {
        match self {
            Variadic::Resolved(v) => v.len(),
            Variadic::Span { len, .. } => *len as usize,
        }
    }
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
    /// Map over children. Works on both Resolved and Span (given pool).
    pub fn map_with_pool<S>(self, _pool: &[usize], f: &mut impl FnMut(R) -> S) -> Variadic<S> {
        match self {
            Variadic::Resolved(v) => Variadic::Resolved(v.into_iter().map(f).collect()),
            Variadic::Span { .. } => panic!("use map_with_pool only after resolve or on Resolved"),
        }
    }
    pub fn map_all<S>(self, f: &mut impl FnMut(R) -> S) -> Variadic<S> {
        match self {
            Variadic::Resolved(v) => Variadic::Resolved(v.into_iter().map(f).collect()),
            _ => panic!("unresolved"),
        }
    }
    pub fn into_vec(self) -> Vec<R> {
        match self {
            Variadic::Resolved(v) => v.into_vec(),
            _ => panic!("unresolved"),
        }
    }
    /// Get the pool slice indices without allocating. Only valid for Span variant.
    pub fn span_indices<'a>(&self, pool: &'a [usize]) -> &'a [usize] {
        match self {
            Variadic::Span { start, len } => {
                &pool[*start as usize..(*start as usize + *len as usize)]
            }
            Variadic::Resolved(_) => panic!("already resolved"),
        }
    }
}

impl<R> IntoIterator for Variadic<R> {
    type Item = R;
    type IntoIter = std::vec::IntoIter<R>;
    fn into_iter(self) -> Self::IntoIter {
        self.into_vec().into_iter()
    }
}

impl<R> std::ops::Index<usize> for Variadic<R> {
    type Output = R;
    fn index(&self, i: usize) -> &R {
        match self {
            Variadic::Resolved(v) => &v[i],
            _ => panic!("unresolved"),
        }
    }
}

impl<R: PartialEq> PartialEq for Variadic<R> {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Variadic::Resolved(a), Variadic::Resolved(b)) => a == b,
            (Variadic::Span { start: s1, len: l1 }, Variadic::Span { start: s2, len: l2 }) => {
                s1 == s2 && l1 == l2
            }
            _ => false,
        }
    }
}
impl<R: Eq> Eq for Variadic<R> {}
impl<R: std::hash::Hash> std::hash::Hash for Variadic<R> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        match self {
            Variadic::Resolved(v) => {
                0u8.hash(state);
                v.hash(state);
            }
            Variadic::Span { start, len } => {
                1u8.hash(state);
                start.hash(state);
                len.hash(state);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// HasVariadic — resolve Variadic::Span fields using the pool
// ---------------------------------------------------------------------------

pub trait HasVariadic {
    fn resolve_spans(&mut self, _pool: &[usize]);
}

#[macro_export]
macro_rules! impl_no_variadic {
    ($($ty:ty),* $(,)?) => {
        $(impl $crate::HasVariadic for $ty {
            fn resolve_spans(&mut self, __pool: &[usize]) {}
        })*
    };
}

// ---------------------------------------------------------------------------
// Internal: collect children from a node via Functor::map
// ---------------------------------------------------------------------------

pub fn collect_children<N: Clone + Functor<usize>>(node: &N) -> smallvec::SmallVec<[usize; 8]> {
    let mut ch = smallvec::SmallVec::new();
    node.children_into(&mut ch);
    ch
}

// ---------------------------------------------------------------------------
// Arena
// ---------------------------------------------------------------------------

pub struct Arena<N, const DEDUP: bool = false> {
    nodes: Vec<N>,
    index: Option<ArenaMap<N, usize>>,
    pool: Vec<usize>,
    strings: StringPool,
}

/// Type alias for a deduplicating arena.
pub type HcArena<N> = Arena<N, true>;

impl<N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic> Default
    for Arena<N, false>
{
    fn default() -> Self {
        Self::new()
    }
}

impl<
    N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic,
    const DEDUP: bool,
> Arena<N, DEDUP>
{
    fn new_inner() -> Self {
        Arena {
            nodes: Vec::new(),
            index: if DEDUP {
                Some(ArenaMap::default())
            } else {
                None
            },
            pool: Vec::new(),
            strings: StringPool::new(),
        }
    }
}

impl<N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic>
    Arena<N, false>
{
    /// Create a non-deduplicating arena. Push always appends.
    pub fn new() -> Self {
        Self::new_inner()
    }
}

impl<N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic>
    Arena<N, true>
{
    /// Create a deduplicating arena. Push returns existing Id for identical nodes.
    pub fn new_dedup() -> Self {
        Self::new_inner()
    }

    /// Build a dedup arena from a plain arena by re-interning reachable nodes.
    pub fn from_arena(arena: &Arena<N, false>, root: Id) -> (Self, Id) {
        let mut hc = Self::new_dedup();
        let mut mapping: Vec<usize> = vec![0; arena.nodes.len()];
        enum Task {
            Enter(usize),
            Eval(usize),
        }
        let mut visited = vec![false; arena.nodes.len()];
        let mut stack = vec![Task::Enter(root.0)];
        let mut ch = smallvec::SmallVec::<[usize; 8]>::new();
        while let Some(task) = stack.pop() {
            match task {
                Task::Enter(i) => {
                    if visited[i] {
                        continue;
                    }
                    visited[i] = true;
                    stack.push(Task::Eval(i));
                    arena.nodes[i].children_into(&mut ch);
                    for &c in ch.iter().rev() {
                        if !visited[c] {
                            stack.push(Task::Enter(c));
                        }
                    }
                }
                Task::Eval(i) => {
                    let remapped = arena.nodes[i].map_ref(|&c: &usize| mapping[c]);
                    mapping[i] = hc.push(remapped).0;
                }
            }
        }
        (hc, Id(mapping[root.0]))
    }
}

impl<
    N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic,
    const DEDUP: bool,
> Arena<N, DEDUP>
{
    /// Push a node. When DEDUP=true, returns existing Id if structurally identical.
    /// When DEDUP=false, always appends.
    pub fn push(&mut self, node: N) -> Id {
        let mut resolved = node;
        resolved.resolve_spans(&self.pool);
        if let Some(ref index) = self.index
            && let Some(&idx) = index.get(&resolved)
        {
            return Id(idx);
        }
        let idx = self.nodes.len();
        if let Some(ref mut index) = self.index {
            index.insert(resolved.clone(), idx);
        }
        self.nodes.push(resolved);
        Id(idx)
    }

    pub fn len(&self) -> usize {
        self.nodes.len()
    }
    pub fn is_empty(&self) -> bool {
        self.nodes.is_empty()
    }
    pub fn get(&self, id: Id) -> &N {
        &self.nodes[id.0]
    }

    pub fn alloc_children(&mut self, children: &[Id]) -> Variadic<usize> {
        let start = self.pool.len() as u32;
        self.pool.extend(children.iter().map(|id| id.0));
        Variadic::Span {
            start,
            len: children.len() as u32,
        }
    }

    pub fn pool(&self) -> &[usize] {
        &self.pool
    }

    pub fn intern_str(&mut self, s: &str) -> StringId {
        self.strings.intern(s)
    }

    pub fn get_str(&self, id: StringId) -> &str {
        self.strings.get(id)
    }

    /// Nodes are stored pre-resolved, so this is just a clone.
    pub fn resolve_node(&self, node: &N) -> N {
        node.clone()
    }

    /// Map a node's children without cloning the node or heap-allocating
    /// for Variadic spans. Reads child indices directly from the pool.
    pub fn map_node<A>(
        &self,
        id: Id,
        mut f: impl FnMut(usize) -> A,
    ) -> <N as Functor<usize>>::Mapped<A>
    where
        N: Functor<usize>,
        A: Clone,
    {
        self.nodes[id.0].clone().map(|c: usize| f(c))
    }
}

// ---------------------------------------------------------------------------

// ===========================================================================
// ArenaView — arena + memo strategy
// ===========================================================================

/// A view of an arena paired with a memoization strategy.
///
/// Use `arena.with_strategy::<Sparse>()` to get a view that uses hash-map
/// backed tables instead of dense vectors. All rooted traversals are
/// available on `ArenaView` and are monomorphized per strategy.
pub struct ArenaView<'a, N, const DEDUP: bool, M: MemoStrategy> {
    arena: &'a Arena<N, DEDUP>,
    _m: std::marker::PhantomData<M>,
}

impl<
    N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic,
    const DEDUP: bool,
> Arena<N, DEDUP>
{
    /// Create a view with a specific memoization strategy.
    ///
    /// ```ignore
    /// // Dense (default) — same as calling arena.fold() directly
    /// arena.with_strategy::<Dense>().fold(root, alg);
    /// // Sparse — hash-map backed, O(reachable) space
    /// arena.with_strategy::<Sparse>().fold(root, alg);
    /// ```
    pub fn with_strategy<M: MemoStrategy>(&self) -> ArenaView<'_, N, DEDUP, M> {
        ArenaView {
            arena: self,
            _m: std::marker::PhantomData,
        }
    }
}

// ===========================================================================
// Schemes on ArenaView (parameterized over MemoStrategy)
// ===========================================================================

impl<'a, N, const DEDUP: bool, M: MemoStrategy> ArenaView<'a, N, DEDUP, M>
where
    N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic,
{
    /// Bottom-up fold (catamorphism).
    pub fn fold<A: Clone>(&self, root: Id, alg: impl Fn(<N as Functor<usize>>::Mapped<A>) -> A) -> A
    where
        N: Functor<usize>,
    {
        let mut res = M::Memo::<A>::new(self.arena.nodes.len());
        enum Task {
            Enter(usize),
            Eval(usize),
        }
        let mut stack = vec![Task::Enter(root.0)];
        let mut ch_buf = smallvec::SmallVec::<[usize; 8]>::new();
        while let Some(task) = stack.pop() {
            match task {
                Task::Enter(i) => {
                    if !M::NO_MEMO && res.get(i).is_some() {
                        continue;
                    }
                    stack.push(Task::Eval(i));
                    self.arena.nodes[i].children_into(&mut ch_buf);
                    for &c in ch_buf.iter().rev() {
                        if M::NO_MEMO || res.get(c).is_none() {
                            stack.push(Task::Enter(c));
                        }
                    }
                }
                Task::Eval(i) => {
                    if !M::NO_MEMO && res.get(i).is_some() {
                        continue;
                    }
                    let node =
                        self.arena.nodes[i].map_ref(|c: &usize| res.get(*c).unwrap().clone());
                    res.set(i, alg(node));
                }
            }
        }
        res.take(root.0).unwrap()
    }

    /// Like `fold` but the algebra receives borrowed children (`N<&A>`).
    pub fn fold_ref<A>(
        &self,
        root: Id,
        alg: impl for<'b> Fn(<N as Functor<usize>>::Mapped<&'b A>) -> A,
    ) -> A
    where
        N: Functor<usize>,
    {
        let mut res = M::Memo::<A>::new(self.arena.nodes.len());
        enum Task {
            Enter(usize),
            Eval(usize),
        }
        let mut stack = vec![Task::Enter(root.0)];
        let mut ch_buf = smallvec::SmallVec::<[usize; 8]>::new();
        while let Some(task) = stack.pop() {
            match task {
                Task::Enter(i) => {
                    if !M::NO_MEMO && res.get(i).is_some() {
                        continue;
                    }
                    stack.push(Task::Eval(i));
                    self.arena.nodes[i].children_into(&mut ch_buf);
                    for &c in ch_buf.iter().rev() {
                        if M::NO_MEMO || res.get(c).is_none() {
                            stack.push(Task::Enter(c));
                        }
                    }
                }
                Task::Eval(i) => {
                    if !M::NO_MEMO && res.get(i).is_some() {
                        continue;
                    }
                    let node = self.arena.nodes[i].map_ref(|c: &usize| res.get(*c).unwrap());
                    res.set(i, alg(node));
                }
            }
        }
        res.take(root.0).unwrap()
    }

    /// Bottom-up fold with mutable state.
    pub fn fold_mut<A: Clone, S>(
        &self,
        root: Id,
        state: &mut S,
        alg: impl Fn(<N as Functor<usize>>::Mapped<A>, &mut S) -> A,
    ) -> A
    where
        N: Functor<usize>,
    {
        let mut res = M::Memo::<A>::new(self.arena.nodes.len());
        let mut visited = M::Visit::new(self.arena.nodes.len());
        enum Task {
            Enter(usize),
            Eval(usize),
        }
        let mut stack = vec![Task::Enter(root.0)];
        let mut ch = smallvec::SmallVec::<[usize; 8]>::new();
        while let Some(task) = stack.pop() {
            match task {
                Task::Enter(i) => {
                    if visited.visited(i) {
                        continue;
                    }
                    visited.mark(i);
                    stack.push(Task::Eval(i));
                    self.arena.nodes[i].children_into(&mut ch);
                    for &c in ch.iter().rev() {
                        if !visited.visited(c) {
                            stack.push(Task::Enter(c));
                        }
                    }
                }
                Task::Eval(i) => {
                    if res.get(i).is_some() {
                        continue;
                    }
                    let node =
                        self.arena.nodes[i].map_ref(|&c: &usize| res.get(c).unwrap().clone());
                    res.set(i, alg(node, state));
                }
            }
        }
        res.take(root.0).unwrap()
    }

    /// Paramorphism — fold where each child carries both its original
    /// arena `Id` and its folded result `A`.
    pub fn fold_with_ids<A: Clone>(
        &self,
        root: Id,
        alg: impl Fn(<N as Functor<usize>>::Mapped<(Id, A)>) -> A,
    ) -> A
    where
        N: Functor<usize>,
    {
        let mut res = M::Memo::<A>::new(self.arena.nodes.len());
        let mut visited = M::Visit::new(self.arena.nodes.len());
        enum Task {
            Enter(usize),
            Eval(usize),
        }
        let mut stack = vec![Task::Enter(root.0)];
        let mut ch = smallvec::SmallVec::<[usize; 8]>::new();
        while let Some(task) = stack.pop() {
            match task {
                Task::Enter(i) => {
                    if visited.visited(i) {
                        continue;
                    }
                    visited.mark(i);
                    stack.push(Task::Eval(i));
                    self.arena.nodes[i].children_into(&mut ch);
                    for &c in ch.iter().rev() {
                        if !visited.visited(c) {
                            stack.push(Task::Enter(c));
                        }
                    }
                }
                Task::Eval(i) => {
                    if res.get(i).is_some() {
                        continue;
                    }
                    let node = self.arena.nodes[i]
                        .map_ref(|&c: &usize| (Id(c), res.get(c).unwrap().clone()));
                    res.set(i, alg(node));
                }
            }
        }
        res.take(root.0).unwrap()
    }

    /// Histomorphism — fold with lookback into children's subtrees.
    pub fn fold_with_history<A: Clone>(
        &self,
        root: Id,
        alg: impl Fn(<N as Functor<usize>>::Mapped<&Ann<A>>) -> A,
    ) -> A
    where
        N: Functor<usize>,
    {
        let mut res = M::Memo::<Ann<A>>::new(self.arena.nodes.len());
        let mut visited = M::Visit::new(self.arena.nodes.len());
        enum Task {
            Enter(usize),
            Eval(usize),
        }
        let mut stack = vec![Task::Enter(root.0)];
        let mut ch = smallvec::SmallVec::<[usize; 8]>::new();
        while let Some(task) = stack.pop() {
            match task {
                Task::Enter(i) => {
                    if visited.visited(i) {
                        continue;
                    }
                    visited.mark(i);
                    stack.push(Task::Eval(i));
                    self.arena.nodes[i].children_into(&mut ch);
                    for &c in ch.iter().rev() {
                        if !visited.visited(c) {
                            stack.push(Task::Enter(c));
                        }
                    }
                }
                Task::Eval(i) => {
                    if res.get(i).is_some() {
                        continue;
                    }
                    let node = self.arena.nodes[i].map_ref(|&c: &usize| res.get(c).unwrap());
                    let value = alg(node);
                    let children = collect_children(&self.arena.nodes[i]);
                    res.set(i, Ann { value, children });
                }
            }
        }
        res.take(root.0).unwrap().value
    }

    /// Zygomorphism — two folds in one pass where the main fold can see
    /// the auxiliary fold's results.
    pub fn fold_with_aux<A: Clone, B: Clone>(
        &self,
        root: Id,
        aux: impl Fn(<N as Functor<usize>>::Mapped<B>) -> B,
        main: impl Fn(<N as Functor<usize>>::Mapped<(A, B)>) -> A,
    ) -> A
    where
        N: Functor<usize>,
    {
        let mut res = M::Memo::<(A, B)>::new(self.arena.nodes.len());
        let mut visited = M::Visit::new(self.arena.nodes.len());
        enum Task {
            Enter(usize),
            Eval(usize),
        }
        let mut stack = vec![Task::Enter(root.0)];
        let mut ch = smallvec::SmallVec::<[usize; 8]>::new();
        while let Some(task) = stack.pop() {
            match task {
                Task::Enter(i) => {
                    if visited.visited(i) {
                        continue;
                    }
                    visited.mark(i);
                    stack.push(Task::Eval(i));
                    self.arena.nodes[i].children_into(&mut ch);
                    for &c in ch.iter().rev() {
                        if !visited.visited(c) {
                            stack.push(Task::Enter(c));
                        }
                    }
                }
                Task::Eval(i) => {
                    if res.get(i).is_some() {
                        continue;
                    }
                    let b = aux(
                        self.arena.nodes[i].map_ref(|&c: &usize| res.get(c).unwrap().1.clone())
                    );
                    let a =
                        main(self.arena.nodes[i].map_ref(|&c: &usize| res.get(c).unwrap().clone()));
                    res.set(i, (a, b));
                }
            }
        }
        res.take(root.0).unwrap().0
    }

    /// Mutual recursion — two folds that depend on each other.
    pub fn fold_pair<A: Clone, B: Clone>(
        &self,
        root: Id,
        alg_a: impl Fn(<N as Functor<usize>>::Mapped<(A, B)>) -> A,
        alg_b: impl Fn(<N as Functor<usize>>::Mapped<(A, B)>) -> B,
    ) -> (A, B)
    where
        N: Functor<usize>,
    {
        let mut res = M::Memo::<(A, B)>::new(self.arena.nodes.len());
        let mut visited = M::Visit::new(self.arena.nodes.len());
        enum Task {
            Enter(usize),
            Eval(usize),
        }
        let mut stack = vec![Task::Enter(root.0)];
        let mut ch = smallvec::SmallVec::<[usize; 8]>::new();
        while let Some(task) = stack.pop() {
            match task {
                Task::Enter(i) => {
                    if visited.visited(i) {
                        continue;
                    }
                    visited.mark(i);
                    stack.push(Task::Eval(i));
                    self.arena.nodes[i].children_into(&mut ch);
                    for &c in ch.iter().rev() {
                        if !visited.visited(c) {
                            stack.push(Task::Enter(c));
                        }
                    }
                }
                Task::Eval(i) => {
                    if res.get(i).is_some() {
                        continue;
                    }
                    let for_a =
                        self.arena.nodes[i].map_ref(|&c: &usize| res.get(c).unwrap().clone());
                    let for_b =
                        self.arena.nodes[i].map_ref(|&c: &usize| res.get(c).unwrap().clone());
                    let a = alg_a(for_a);
                    let b = alg_b(for_b);
                    res.set(i, (a, b));
                }
            }
        }
        res.take(root.0).unwrap()
    }

    /// Prepromorphism — apply a natural transformation `N → N` to each
    /// node before folding.
    pub fn prefold<A: Clone>(
        &self,
        root: Id,
        pre: impl Fn(N) -> N,
        alg: impl Fn(<N as Functor<usize>>::Mapped<A>) -> A,
    ) -> A
    where
        N: Functor<usize>,
    {
        let mut new_arena: Arena<N> = Arena::new();
        let mut mapping = M::Mapping::new(self.arena.nodes.len());
        let mut visited = M::Visit::new(self.arena.nodes.len());
        enum Task {
            Enter(usize),
            Eval(usize),
        }
        let mut stack = vec![Task::Enter(root.0)];
        let mut ch = smallvec::SmallVec::<[usize; 8]>::new();
        while let Some(task) = stack.pop() {
            match task {
                Task::Enter(i) => {
                    if visited.visited(i) {
                        continue;
                    }
                    visited.mark(i);
                    stack.push(Task::Eval(i));
                    self.arena.nodes[i].children_into(&mut ch);
                    for &c in ch.iter().rev() {
                        if !visited.visited(c) {
                            stack.push(Task::Enter(c));
                        }
                    }
                }
                Task::Eval(i) => {
                    let node = pre(self.arena.nodes[i].map_ref(|&c: &usize| mapping.get(c)));
                    let id = new_arena.push(node);
                    mapping.set(i, id.0);
                }
            }
        }
        new_arena.fold(Id(mapping.get(root.0)), alg)
    }

    /// Bottom-up transform — rewrite rules applied post-order.
    pub fn transform(&self, root: Id, rule: impl Fn(N) -> N) -> (Arena<N>, Id) {
        self.rewrite(root, |node, arena| arena.push(rule(node)))
    }

    /// Bottom-up rewrite — the full-power transform.
    pub fn rewrite(&self, root: Id, rule: impl Fn(N, &mut Arena<N>) -> Id) -> (Arena<N>, Id) {
        let mut new_arena: Arena<N> = Arena::new();
        let mut mapping = M::Mapping::new(self.arena.nodes.len());
        let mut visited = M::Visit::new(self.arena.nodes.len());
        enum Task {
            Enter(usize),
            Eval(usize),
        }
        let mut stack = vec![Task::Enter(root.0)];
        let mut ch = smallvec::SmallVec::<[usize; 8]>::new();
        while let Some(task) = stack.pop() {
            match task {
                Task::Enter(i) => {
                    if visited.visited(i) {
                        continue;
                    }
                    visited.mark(i);
                    stack.push(Task::Eval(i));
                    self.arena.nodes[i].children_into(&mut ch);
                    for &c in ch.iter().rev() {
                        if !visited.visited(c) {
                            stack.push(Task::Enter(c));
                        }
                    }
                }
                Task::Eval(i) => {
                    let remapped = self.arena.nodes[i].map_ref(|&c: &usize| mapping.get(c));
                    let id = rule(remapped, &mut new_arena);
                    mapping.set(i, id.0);
                }
            }
        }
        (new_arena, Id(mapping.get(root.0)))
    }

    /// Fold with early exit (short-circuit).
    pub fn fold_short<A: Clone>(
        &self,
        root: Id,
        alg: impl Fn(<N as Functor<usize>>::Mapped<A>) -> Result<A, A>,
    ) -> A
    where
        N: Functor<usize>,
    {
        let mut res = M::Memo::<A>::new(self.arena.nodes.len());
        let mut visited = M::Visit::new(self.arena.nodes.len());
        enum Task {
            Enter(usize),
            Eval(usize),
        }
        let mut stack = vec![Task::Enter(root.0)];
        let mut ch = smallvec::SmallVec::<[usize; 8]>::new();
        while let Some(task) = stack.pop() {
            match task {
                Task::Enter(i) => {
                    if visited.visited(i) {
                        continue;
                    }
                    visited.mark(i);
                    stack.push(Task::Eval(i));
                    self.arena.nodes[i].children_into(&mut ch);
                    for &c in ch.iter().rev() {
                        if !visited.visited(c) {
                            stack.push(Task::Enter(c));
                        }
                    }
                }
                Task::Eval(i) => {
                    if res.get(i).is_some() {
                        continue;
                    }
                    let node =
                        self.arena.nodes[i].map_ref(|&c: &usize| res.get(c).unwrap().clone());
                    match alg(node) {
                        Ok(a) => {
                            res.set(i, a);
                        }
                        Err(a) => return a,
                    }
                }
            }
        }
        res.take(root.0).unwrap()
    }

    /// Fold where the algebra sees both the original node and the mapped node.
    pub fn fold_with_original<A: Clone>(
        &self,
        root: Id,
        alg: impl Fn(&N, <N as Functor<usize>>::Mapped<A>) -> A,
    ) -> A
    where
        N: Functor<usize>,
    {
        let mut res = M::Memo::<A>::new(self.arena.nodes.len());
        let mut visited = M::Visit::new(self.arena.nodes.len());
        enum Task {
            Enter(usize),
            Eval(usize),
        }
        let mut stack = vec![Task::Enter(root.0)];
        let mut ch = smallvec::SmallVec::<[usize; 8]>::new();
        while let Some(task) = stack.pop() {
            match task {
                Task::Enter(i) => {
                    if visited.visited(i) {
                        continue;
                    }
                    visited.mark(i);
                    stack.push(Task::Eval(i));
                    self.arena.nodes[i].children_into(&mut ch);
                    for &c in ch.iter().rev() {
                        if !visited.visited(c) {
                            stack.push(Task::Enter(c));
                        }
                    }
                }
                Task::Eval(i) => {
                    if res.get(i).is_some() {
                        continue;
                    }
                    let mapped =
                        self.arena.nodes[i].map_ref(|&c: &usize| res.get(c).unwrap().clone());
                    res.set(i, alg(&self.arena.nodes[i], mapped));
                }
            }
        }
        res.take(root.0).unwrap()
    }

    /// Top-down transform — rewrite rules applied pre-order (root first).
    pub fn rewrite_down(&self, root: Id, rule: impl Fn(N) -> N) -> (Arena<N>, Id) {
        enum Task {
            Enter(usize),
            Build(usize),
        }
        let mut new_arena: Arena<N> = Arena::new();
        let mut mapping = M::Mapping::new(self.arena.nodes.len());
        let mut rewritten = M::Memo::<N>::new(self.arena.nodes.len());
        let mut order: Vec<usize> = Vec::new();
        let mut work = vec![Task::Enter(root.0)];
        let mut visited = M::Visit::new(self.arena.nodes.len());
        while let Some(task) = work.pop() {
            match task {
                Task::Enter(i) => {
                    if visited.visited(i) {
                        continue;
                    }
                    visited.mark(i);
                    let rw = rule(self.arena.nodes[i].clone());
                    let children = collect_children(&rw);
                    rewritten.set(i, rw);
                    work.push(Task::Build(i));
                    for &c in children.iter().rev() {
                        if !visited.visited(c) {
                            work.push(Task::Enter(c));
                        }
                    }
                }
                Task::Build(i) => order.push(i),
            }
        }
        for i in order {
            let rw = rewritten.take(i).unwrap();
            let remapped = rw.map(|c: usize| mapping.get(c));
            let id = new_arena.push(remapped);
            mapping.set(i, id.0);
        }
        (new_arena, Id(mapping.get(root.0)))
    }
}

// ===========================================================================
// Schemes on Arena — delegate to ArenaView<Dense>
// ===========================================================================

impl<
    N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic,
    const DEDUP: bool,
> Arena<N, DEDUP>
{
    /// Bottom-up fold (catamorphism). Uses dense memoization by default.
    /// For sparse memoization, use `arena.with_strategy::<Sparse>().fold(root, alg)`.
    pub fn fold<A: Clone>(&self, root: Id, alg: impl Fn(<N as Functor<usize>>::Mapped<A>) -> A) -> A
    where
        N: Functor<usize>,
    {
        self.with_strategy::<Dense>().fold(root, alg)
    }

    /// Like `fold` but the algebra receives borrowed children (`N<&A>`).
    pub fn fold_ref<A>(
        &self,
        root: Id,
        alg: impl for<'a> Fn(<N as Functor<usize>>::Mapped<&'a A>) -> A,
    ) -> A
    where
        N: Functor<usize>,
    {
        self.with_strategy::<Dense>().fold_ref(root, alg)
    }

    /// Fold every node in the arena in a single O(n) pass. Always dense.
    pub fn fold_all<A: Clone>(
        &self,
        alg: impl Fn(<N as Functor<usize>>::Mapped<A>) -> A,
    ) -> FoldCache<A>
    where
        N: Functor<usize>,
    {
        let mut res: Vec<A> = Vec::with_capacity(self.nodes.len());
        for i in 0..self.nodes.len() {
            let node = self.nodes[i].map_ref(|c: &usize| res[*c].clone());
            res.push(alg(node));
        }
        FoldCache { results: res }
    }

    /// Like `fold_all` but the algebra receives borrowed children (`N<&A>`).
    pub fn fold_all_ref<A>(
        &self,
        alg: impl for<'a> Fn(<N as Functor<usize>>::Mapped<&'a A>) -> A,
    ) -> FoldCache<A>
    where
        N: Functor<usize>,
    {
        let mut res: Vec<A> = Vec::with_capacity(self.nodes.len());
        for i in 0..self.nodes.len() {
            let node = self.nodes[i].map_ref(|c: &usize| &res[*c]);
            res.push(alg(node));
        }
        FoldCache { results: res }
    }

    /// Create a persistent memoized folder.
    pub fn memo_folder<A: Clone>(
        &self,
        alg: impl Fn(<N as Functor<usize>>::Mapped<A>) -> A,
    ) -> MemoFolder<'_, N, A, impl Fn(<N as Functor<usize>>::Mapped<A>) -> A, DEDUP>
    where
        N: Functor<usize>,
    {
        MemoFolder {
            memo: vec![None; self.nodes.len()],
            arena: self,
            alg,
        }
    }

    /// Bottom-up fold with mutable state.
    pub fn fold_mut<A: Clone, S>(
        &self,
        root: Id,
        state: &mut S,
        alg: impl Fn(<N as Functor<usize>>::Mapped<A>, &mut S) -> A,
    ) -> A
    where
        N: Functor<usize>,
    {
        self.with_strategy::<Dense>().fold_mut(root, state, alg)
    }

    /// Paramorphism — fold where each child carries both its original
    /// arena `Id` and its folded result `A`.
    pub fn fold_with_ids<A: Clone>(
        &self,
        root: Id,
        alg: impl Fn(<N as Functor<usize>>::Mapped<(Id, A)>) -> A,
    ) -> A
    where
        N: Functor<usize>,
    {
        self.with_strategy::<Dense>().fold_with_ids(root, alg)
    }

    /// Histomorphism — fold with lookback into children's subtrees.
    pub fn fold_with_history<A: Clone>(
        &self,
        root: Id,
        alg: impl Fn(<N as Functor<usize>>::Mapped<&Ann<A>>) -> A,
    ) -> A
    where
        N: Functor<usize>,
    {
        self.with_strategy::<Dense>().fold_with_history(root, alg)
    }

    /// Zygomorphism — two folds in one pass.
    pub fn fold_with_aux<A: Clone, B: Clone>(
        &self,
        root: Id,
        aux: impl Fn(<N as Functor<usize>>::Mapped<B>) -> B,
        main: impl Fn(<N as Functor<usize>>::Mapped<(A, B)>) -> A,
    ) -> A
    where
        N: Functor<usize>,
    {
        self.with_strategy::<Dense>().fold_with_aux(root, aux, main)
    }

    /// Mutual recursion — two folds that depend on each other.
    pub fn fold_pair<A: Clone, B: Clone>(
        &self,
        root: Id,
        alg_a: impl Fn(<N as Functor<usize>>::Mapped<(A, B)>) -> A,
        alg_b: impl Fn(<N as Functor<usize>>::Mapped<(A, B)>) -> B,
    ) -> (A, B)
    where
        N: Functor<usize>,
    {
        self.with_strategy::<Dense>().fold_pair(root, alg_a, alg_b)
    }

    /// Prepromorphism — normalize then fold.
    pub fn prefold<A: Clone>(
        &self,
        root: Id,
        pre: impl Fn(N) -> N,
        alg: impl Fn(<N as Functor<usize>>::Mapped<A>) -> A,
    ) -> A
    where
        N: Functor<usize>,
    {
        self.with_strategy::<Dense>().prefold(root, pre, alg)
    }

    /// Bottom-up transform.
    pub fn transform(&self, root: Id, rule: impl Fn(N) -> N) -> (Arena<N>, Id) {
        self.with_strategy::<Dense>().transform(root, rule)
    }

    /// Bottom-up rewrite — the full-power transform.
    pub fn rewrite(&self, root: Id, rule: impl Fn(N, &mut Arena<N>) -> Id) -> (Arena<N>, Id) {
        self.with_strategy::<Dense>().rewrite(root, rule)
    }

    /// Fold with early exit (short-circuit).
    pub fn fold_short<A: Clone>(
        &self,
        root: Id,
        alg: impl Fn(<N as Functor<usize>>::Mapped<A>) -> Result<A, A>,
    ) -> A
    where
        N: Functor<usize>,
    {
        self.with_strategy::<Dense>().fold_short(root, alg)
    }
}

// ===========================================================================
// Annotated node for fold_with_history
// ===========================================================================

/// Cached fold results from `Arena::fold_all`. Look up any node's result by Id.
pub struct FoldCache<A> {
    results: Vec<A>,
}

impl<A> std::ops::Index<Id> for FoldCache<A> {
    type Output = A;
    fn index(&self, id: Id) -> &A {
        &self.results[id.0]
    }
}

impl<A> FoldCache<A> {
    pub fn get(&self, id: Id) -> &A {
        &self.results[id.0]
    }
}

/// Persistent memoized folder. Explicit heap stack traversal — no recursion,
/// no stack overflow. Shared subtrees computed at most once across all `get` calls.
pub struct MemoFolder<'a, N, A, F, const DEDUP: bool = false> {
    memo: Vec<Option<A>>,
    arena: &'a Arena<N, DEDUP>,
    alg: F,
}

impl<'a, N, A, F, const DEDUP: bool> MemoFolder<'a, N, A, F, DEDUP>
where
    N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic,
    A: Clone,
    F: Fn(<N as Functor<usize>>::Mapped<A>) -> A,
{
    /// Get the fold result for `root`. Traverses only unvisited nodes
    /// reachable from `root`. Previously computed subtrees are reused.
    pub fn get(&mut self, root: Id) -> &A {
        if self.memo[root.0].is_some() {
            return self.memo[root.0].as_ref().unwrap();
        }
        enum Task {
            Enter(usize),
            Eval(usize),
        }
        let mut stack = vec![Task::Enter(root.0)];
        let mut ch_buf = smallvec::SmallVec::<[usize; 8]>::new();
        while let Some(task) = stack.pop() {
            match task {
                Task::Enter(i) => {
                    if self.memo[i].is_some() {
                        continue;
                    }
                    stack.push(Task::Eval(i));
                    self.arena.nodes[i].children_into(&mut ch_buf);
                    for &c in ch_buf.iter().rev() {
                        if self.memo[c].is_none() {
                            stack.push(Task::Enter(c));
                        }
                    }
                }
                Task::Eval(i) => {
                    if self.memo[i].is_some() {
                        continue;
                    }
                    let node = self.arena.nodes[i]
                        .map_ref(|c: &usize| self.memo[*c].as_ref().unwrap().clone());
                    self.memo[i] = Some((self.alg)(node));
                }
            }
        }
        self.memo[root.0].as_ref().unwrap()
    }
}

/// Annotated result for `fold_with_history`.
///
/// - `value`: the folded result for this node
/// - `children`: arena indices of this node's direct children, enabling
///   lookback into grandchildren via `arena.get(Id(child))` or by
///   inspecting the `Ann` stored at those indices
pub struct Ann<A> {
    pub value: A,
    pub children: smallvec::SmallVec<[usize; 8]>,
}

// ===========================================================================
// Support types
// ===========================================================================

/// Used by unfold_short to signal "stop unfolding, reuse this id".
pub enum Seed<S> {
    Continue(S),
    Done(Id),
}

// ===========================================================================
// Internal: iterative unfold engine (explicit stack, no recursion)
// ===========================================================================
//
// Two stacks: `work` (tasks to do) and `results` (completed Ids).
// Expand pushes a Build frame then child Expand frames (reversed).
// Build pops N child results, remaps the node, pushes into arena.

enum AnaTask<N, S> {
    Expand(S),
    Build(N, usize), // node + child count
}

enum ApoTask<N, S> {
    Expand(S),
    Build(N, usize),
    Literal(Id), // Done(id) — push directly to results
}

fn remap_and_push<N>(node: N, n: usize, results: &mut Vec<Id>, push: &mut impl FnMut(N) -> Id)
where
    N: Functor<usize, Mapped<usize> = N>,
{
    let start = results.len() - n;
    let child_ids: Vec<usize> = results.drain(start..).map(|id| id.0).collect();
    let mut idx = 0;
    let remapped = node.map(|_: usize| {
        let id = child_ids[idx];
        idx += 1;
        id
    });
    results.push(push(remapped));
}

// ===========================================================================
// Unfolds — iterative, stack-safe
// ===========================================================================

/// Anamorphism — build a tree from a seed, top-down.
///
/// The coalgebra takes a seed `S` and returns `(N, Vec<S>)`: one node
/// layer plus seeds for each child. Expansion continues until a seed
/// produces an empty `Vec` (a leaf). Iterative — uses an explicit
/// stack, safe for arbitrarily deep trees.
pub fn unfold<N, S>(arena: &mut Arena<N>, seed: S, coalg: impl Fn(S) -> (N, Vec<S>)) -> Id
where
    N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic,
{
    let mut work: Vec<AnaTask<N, S>> = vec![AnaTask::Expand(seed)];
    let mut results: Vec<Id> = Vec::new();
    while let Some(task) = work.pop() {
        match task {
            AnaTask::Expand(s) => {
                let (node, child_seeds) = coalg(s);
                let n = child_seeds.len();
                work.push(AnaTask::Build(node, n));
                for cs in child_seeds.into_iter().rev() {
                    work.push(AnaTask::Expand(cs));
                }
            }
            AnaTask::Build(node, n) => {
                remap_and_push(node, n, &mut results, &mut |n| arena.push(n));
            }
        }
    }
    results.pop().unwrap()
}

/// Apomorphism — unfold with early exit.
///
/// Like `unfold`, but child seeds are `Seed<S>`:
/// - `Seed::Continue(s)` — keep expanding this child
/// - `Seed::Done(id)` — stop here, reuse an existing arena node
///
/// Use this to graft pre-built subtrees into a tree being unfolded,
/// avoiding redundant expansion.
pub fn unfold_short<N, S>(
    arena: &mut Arena<N>,
    seed: S,
    coalg: impl Fn(S) -> (N, Vec<Seed<S>>),
) -> Id
where
    N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic,
{
    let mut work: Vec<ApoTask<N, S>> = vec![ApoTask::Expand(seed)];
    let mut results: Vec<Id> = Vec::new();
    while let Some(task) = work.pop() {
        match task {
            ApoTask::Expand(s) => {
                let (node, child_seeds) = coalg(s);
                let n = child_seeds.len();
                work.push(ApoTask::Build(node, n));
                for cs in child_seeds.into_iter().rev() {
                    match cs {
                        Seed::Continue(s) => work.push(ApoTask::Expand(s)),
                        Seed::Done(id) => work.push(ApoTask::Literal(id)),
                    }
                }
            }
            ApoTask::Build(node, n) => {
                remap_and_push(node, n, &mut results, &mut |n| arena.push(n));
            }
            ApoTask::Literal(id) => {
                results.push(id);
            }
        }
    }
    results.pop().unwrap()
}

/// Postpromorphism — unfold with a normalization pass after each layer.
///
/// After the coalgebra produces a node and its children are remapped
/// into the arena, `post` rewrites the node before it is pushed.
/// Use this to enforce canonical forms during construction — e.g.,
/// sorting commutative operands so that hash-consing is maximized.
pub fn postunfold<N, S>(
    arena: &mut Arena<N>,
    seed: S,
    post: impl Fn(N) -> N,
    coalg: impl Fn(S) -> (N, Vec<S>),
) -> Id
where
    N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic,
{
    let mut work: Vec<AnaTask<N, S>> = vec![AnaTask::Expand(seed)];
    let mut results: Vec<Id> = Vec::new();
    while let Some(task) = work.pop() {
        match task {
            AnaTask::Expand(s) => {
                let (node, child_seeds) = coalg(s);
                let n = child_seeds.len();
                work.push(AnaTask::Build(node, n));
                for cs in child_seeds.into_iter().rev() {
                    work.push(AnaTask::Expand(cs));
                }
            }
            AnaTask::Build(node, n) => {
                let start = results.len() - n;
                let child_ids: Vec<usize> = results.drain(start..).map(|id| id.0).collect();
                let mut idx = 0;
                let remapped = node.map(|_: usize| {
                    let id = child_ids[idx];
                    idx += 1;
                    id
                });
                results.push(arena.push(post(remapped)));
            }
        }
    }
    results.pop().unwrap()
}

// ===========================================================================
// HcArena unfolds — hash-consed, iterative
// ===========================================================================

/// Anamorphism into HcArena — structurally identical subtrees are
/// deduplicated via hash-consing. Otherwise identical to `unfold`.
pub fn unfold_hc<N, S>(arena: &mut HcArena<N>, seed: S, coalg: impl Fn(S) -> (N, Vec<S>)) -> Id
where
    N: Clone + Functor<usize, Mapped<usize> = N> + std::hash::Hash + Eq + HasVariadic,
{
    let mut work: Vec<AnaTask<N, S>> = vec![AnaTask::Expand(seed)];
    let mut results: Vec<Id> = Vec::new();
    while let Some(task) = work.pop() {
        match task {
            AnaTask::Expand(s) => {
                let (node, child_seeds) = coalg(s);
                let n = child_seeds.len();
                work.push(AnaTask::Build(node, n));
                for cs in child_seeds.into_iter().rev() {
                    work.push(AnaTask::Expand(cs));
                }
            }
            AnaTask::Build(node, n) => {
                remap_and_push(node, n, &mut results, &mut |n| arena.push(n));
            }
        }
    }
    results.pop().unwrap()
}

/// Apomorphism into HcArena — unfold with early exit and hash-consing.
/// Otherwise identical to `unfold_short`.
pub fn unfold_short_hc<N, S>(
    arena: &mut HcArena<N>,
    seed: S,
    coalg: impl Fn(S) -> (N, Vec<Seed<S>>),
) -> Id
where
    N: Clone + Functor<usize, Mapped<usize> = N> + std::hash::Hash + Eq + HasVariadic,
{
    let mut work: Vec<ApoTask<N, S>> = vec![ApoTask::Expand(seed)];
    let mut results: Vec<Id> = Vec::new();
    while let Some(task) = work.pop() {
        match task {
            ApoTask::Expand(s) => {
                let (node, child_seeds) = coalg(s);
                let n = child_seeds.len();
                work.push(ApoTask::Build(node, n));
                for cs in child_seeds.into_iter().rev() {
                    match cs {
                        Seed::Continue(s) => work.push(ApoTask::Expand(s)),
                        Seed::Done(id) => work.push(ApoTask::Literal(id)),
                    }
                }
            }
            ApoTask::Build(node, n) => {
                remap_and_push(node, n, &mut results, &mut |n| arena.push(n));
            }
            ApoTask::Literal(id) => {
                results.push(id);
            }
        }
    }
    results.pop().unwrap()
}

// ===========================================================================
// Refolds — iterative
// ===========================================================================

/// Unfold then fold in a single pass — no arena is ever built.
///
/// Also known as a *hylomorphism*. The coalgebra describes what the tree
/// *would* look like (each node + its child seeds), and the algebra
/// consumes it — but intermediate nodes are never stored. They are
/// produced and consumed on the fly using an explicit stack.
///
/// # Example: factorial
///
/// ```ignore
/// refold(
///     5u64,
///     &|n| if n == 0 { (1, vec![]) } else { (n, vec![n - 1]) },
///     &|n, ch| if ch.is_empty() { n } else { n * ch[0] },
/// );
/// ```
///
/// Conceptual tree (never materialized):
///
/// ```text
/// 5 ── 4 ── 3 ── 2 ── 1 ── 1(base)
/// ```
///
/// Execution on the internal stack:
///
/// 1. Expand seeds top-down: 5 → 4 → 3 → 2 → 1 → 0(base)
/// 2. Fold back up:
///    - Build(1, 0 children) → 1
///    - Build(1, \[1\])        → 1×1 = 1
///    - Build(2, \[1\])        → 2×1 = 2
///    - Build(3, \[2\])        → 3×2 = 6
///    - Build(4, \[6\])        → 4×6 = 24
///    - Build(5, \[24\])       → 5×24 = 120
///
/// This gives you the composability of separating "how to build the
/// structure" from "how to evaluate it" without paying for
/// materialization.
pub fn refold<S, A>(seed: S, coalg: &dyn Fn(S) -> (A, Vec<S>), alg: &dyn Fn(A, Vec<A>) -> A) -> A {
    enum Task<S, A> {
        Expand(S),
        Build(A, usize),
    }
    let mut work: Vec<Task<S, A>> = vec![Task::Expand(seed)];
    let mut results: Vec<A> = Vec::new();
    while let Some(task) = work.pop() {
        match task {
            Task::Expand(s) => {
                let (node, child_seeds) = coalg(s);
                let n = child_seeds.len();
                work.push(Task::Build(node, n));
                for cs in child_seeds.into_iter().rev() {
                    work.push(Task::Expand(cs));
                }
            }
            Task::Build(node, n) => {
                let start = results.len() - n;
                let child_results: Vec<A> = results.drain(start..).collect();
                results.push(alg(node, child_results));
            }
        }
    }
    results.pop().unwrap()
}

/// Dynamorphism — unfold a seed into an arena, then fold with history.
///
/// Combines `unfold` + `fold_with_history`. The coalgebra builds the
/// tree, then the algebra folds it with `Ann<A>` lookback into
/// children's subtrees. Use this when you need both generative and
/// lookback power — e.g., computing Fibonacci by unfolding the call
/// tree and folding with access to two levels of results.
pub fn refold_with_history<N, S, A: Clone>(
    seed: S,
    coalg: impl Fn(S) -> (N, Vec<S>),
    alg: impl Fn(<N as Functor<usize>>::Mapped<&Ann<A>>) -> A,
) -> A
where
    N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic,
{
    let mut arena = Arena::new();
    let root = unfold(&mut arena, seed, coalg);
    arena.fold_with_history(root, alg)
}

/// Chronomorphism — unfold into an HcArena, then fold with history.
///
/// Like `refold_with_history` but uses hash-consing: structurally
/// identical subtrees are deduplicated during the unfold phase, and
/// the fold only visits each unique subtree once. Use this when the
/// unfolded tree has significant sharing (e.g., overlapping subproblems
/// in dynamic programming).
pub fn refold_full<N, S, A: Clone>(
    seed: S,
    coalg: impl Fn(S) -> (N, Vec<S>),
    alg: impl Fn(<N as Functor<usize>>::Mapped<&Ann<A>>) -> A,
) -> A
where
    N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic,
{
    let mut arena: HcArena<N> = Arena::new_dedup();
    let root = unfold_hc(&mut arena, seed, coalg);
    arena.fold_with_history(root, alg)
}

// ===========================================================================
// Additional schemes on Arena — delegate to ArenaView<Dense>
// ===========================================================================

impl<
    N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic,
    const DEDUP: bool,
> Arena<N, DEDUP>
{
    /// Fold where the algebra sees both the original node and the mapped node.
    pub fn fold_with_original<A: Clone>(
        &self,
        root: Id,
        alg: impl Fn(&N, <N as Functor<usize>>::Mapped<A>) -> A,
    ) -> A
    where
        N: Functor<usize>,
    {
        self.with_strategy::<Dense>().fold_with_original(root, alg)
    }

    /// Top-down transform — rewrite rules applied pre-order (root first).
    pub fn rewrite_down(&self, root: Id, rule: impl Fn(N) -> N) -> (Arena<N>, Id) {
        self.with_strategy::<Dense>().rewrite_down(root, rule)
    }
}

// ===========================================================================
// Arena::set — in-place mutation (non-dedup only)
// ===========================================================================

impl<N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic>
    Arena<N, false>
{
    /// Replace the node at `id` in place. Only available on non-dedup arenas.
    pub fn set(&mut self, id: Id, node: N) {
        self.nodes[id.0] = node;
    }
}

// ===========================================================================
// Zipper types — focused navigation with context
// ===========================================================================

/// One step of the descent path: which node we came from and which child
/// slot we descended through.
#[derive(Clone, Debug)]
pub struct Crumb {
    pub node_id: Id,
    pub child_index: usize,
}

// ---------------------------------------------------------------------------
// Shared navigation helpers (used by all zipper types)
// ---------------------------------------------------------------------------

fn zipper_children<N: Clone + Functor<usize>>(node: &N) -> smallvec::SmallVec<[usize; 8]> {
    let mut ch = smallvec::SmallVec::<[usize; 8]>::new();
    node.children_into(&mut ch);
    ch
}

// ---------------------------------------------------------------------------
// Zipper — read-only cursor
// ---------------------------------------------------------------------------

/// Read-only cursor into an arena. Navigate freely, inspect nodes and
/// the path from root. No mutation of the source arena.
pub struct Zipper<'a, N, const DEDUP: bool = false> {
    arena: &'a Arena<N, DEDUP>,
    focus: Id,
    crumbs: Vec<Crumb>,
}

impl<'a, N, const DEDUP: bool> Zipper<'a, N, DEDUP>
where
    N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic,
{
    pub fn new(arena: &'a Arena<N, DEDUP>, root: Id) -> Self {
        Self {
            arena,
            focus: root,
            crumbs: Vec::new(),
        }
    }

    pub fn arena(&self) -> &Arena<N, DEDUP> {
        self.arena
    }
    pub fn focus(&self) -> &N {
        self.arena.get(self.focus)
    }
    pub fn focus_id(&self) -> Id {
        self.focus
    }
    pub fn depth(&self) -> usize {
        self.crumbs.len()
    }
    pub fn path(&self) -> &[Crumb] {
        &self.crumbs
    }

    pub fn child_count(&self) -> usize {
        zipper_children(self.arena.get(self.focus)).len()
    }

    pub fn down(&mut self, child_index: usize) -> bool {
        let ch = zipper_children(self.arena.get(self.focus));
        if child_index >= ch.len() {
            return false;
        }
        self.crumbs.push(Crumb {
            node_id: self.focus,
            child_index,
        });
        self.focus = Id(ch[child_index]);
        true
    }

    pub fn up(&mut self) -> bool {
        match self.crumbs.pop() {
            Some(c) => {
                self.focus = c.node_id;
                true
            }
            None => false,
        }
    }

    pub fn sibling(&mut self, child_index: usize) -> bool {
        if !self.up() {
            return false;
        }
        self.down(child_index)
    }

    pub fn top(&mut self) {
        if !self.crumbs.is_empty() {
            self.focus = self.crumbs[0].node_id;
            self.crumbs.clear();
        }
    }
}

// ---------------------------------------------------------------------------
// ZipperMut — in-place mutation, all parents see the change
// ---------------------------------------------------------------------------

/// Mutable cursor. `set_focus` overwrites the node in place — every parent
/// that references this node (including through hash-consing sharing) sees
/// the update. Only available on non-dedup arenas (mutating a shared node
/// in an HcArena would corrupt the dedup index).
pub struct ZipperMut<'a, N> {
    arena: &'a mut Arena<N, false>,
    focus: Id,
    crumbs: Vec<Crumb>,
}

impl<'a, N> ZipperMut<'a, N>
where
    N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic,
{
    pub fn new(arena: &'a mut Arena<N, false>, root: Id) -> Self {
        Self {
            arena,
            focus: root,
            crumbs: Vec::new(),
        }
    }

    pub fn focus(&self) -> &N {
        self.arena.get(self.focus)
    }
    pub fn focus_id(&self) -> Id {
        self.focus
    }
    pub fn depth(&self) -> usize {
        self.crumbs.len()
    }
    pub fn path(&self) -> &[Crumb] {
        &self.crumbs
    }

    pub fn child_count(&self) -> usize {
        zipper_children(self.arena.get(self.focus)).len()
    }

    pub fn down(&mut self, child_index: usize) -> bool {
        let ch = zipper_children(self.arena.get(self.focus));
        if child_index >= ch.len() {
            return false;
        }
        self.crumbs.push(Crumb {
            node_id: self.focus,
            child_index,
        });
        self.focus = Id(ch[child_index]);
        true
    }

    pub fn up(&mut self) -> bool {
        match self.crumbs.pop() {
            Some(c) => {
                self.focus = c.node_id;
                true
            }
            None => false,
        }
    }

    pub fn sibling(&mut self, child_index: usize) -> bool {
        if !self.up() {
            return false;
        }
        self.down(child_index)
    }

    pub fn top(&mut self) {
        if !self.crumbs.is_empty() {
            self.focus = self.crumbs[0].node_id;
            self.crumbs.clear();
        }
    }

    /// Replace the focused node in place. O(1), no allocation.
    /// All parents sharing this node see the change.
    pub fn set_focus(&mut self, node: N) {
        self.arena.set(self.focus, node);
    }
}

// ---------------------------------------------------------------------------
// ZipperCow — copy-on-write: only the spine from focus to root is rebuilt
// ---------------------------------------------------------------------------

/// Copy-on-write cursor. When you call `set_focus`, the focused node and
/// every ancestor on the descent path are copied into a new arena. Other
/// parents that share the original node are unaffected.
///
/// Call `finish()` to get the new arena and root.
pub struct ZipperCow<'a, N, const DEDUP: bool = false> {
    src: &'a Arena<N, DEDUP>,
    focus: Id,
    crumbs: Vec<Crumb>,
}

impl<'a, N, const DEDUP: bool> ZipperCow<'a, N, DEDUP>
where
    N: Clone + Functor<usize, Mapped<usize> = N> + Eq + std::hash::Hash + HasVariadic,
{
    pub fn new(src: &'a Arena<N, DEDUP>, root: Id) -> Self {
        Self {
            src,
            focus: root,
            crumbs: Vec::new(),
        }
    }

    pub fn src(&self) -> &Arena<N, DEDUP> {
        self.src
    }
    pub fn focus(&self) -> &N {
        self.src.get(self.focus)
    }
    pub fn focus_id(&self) -> Id {
        self.focus
    }
    pub fn depth(&self) -> usize {
        self.crumbs.len()
    }
    pub fn path(&self) -> &[Crumb] {
        &self.crumbs
    }

    pub fn child_count(&self) -> usize {
        zipper_children(self.src.get(self.focus)).len()
    }

    pub fn down(&mut self, child_index: usize) -> bool {
        let ch = zipper_children(self.src.get(self.focus));
        if child_index >= ch.len() {
            return false;
        }
        self.crumbs.push(Crumb {
            node_id: self.focus,
            child_index,
        });
        self.focus = Id(ch[child_index]);
        true
    }

    pub fn up(&mut self) -> bool {
        match self.crumbs.pop() {
            Some(c) => {
                self.focus = c.node_id;
                true
            }
            None => false,
        }
    }

    pub fn sibling(&mut self, child_index: usize) -> bool {
        if !self.up() {
            return false;
        }
        self.down(child_index)
    }

    pub fn top(&mut self) {
        if !self.crumbs.is_empty() {
            self.focus = self.crumbs[0].node_id;
            self.crumbs.clear();
        }
    }

    /// Replace the focused node with `new_node`, then rebuild the spine
    /// from focus to root into a new arena. Returns `(new_arena, new_root)`.
    /// The source arena is untouched.
    pub fn set_focus(&self, new_node: N) -> (Arena<N>, Id) {
        let root = if self.crumbs.is_empty() {
            self.focus
        } else {
            self.crumbs[0].node_id
        };

        let mut dst: Arena<N> = Arena::new();
        let mut mapping: Vec<usize> = vec![0; self.src.len()];

        // Bottom-up traversal of the reachable tree
        enum Task {
            Enter(usize),
            Eval(usize),
        }
        let mut visited = vec![false; self.src.len()];
        let mut stack = vec![Task::Enter(root.0)];
        let mut ch_buf = smallvec::SmallVec::<[usize; 8]>::new();

        while let Some(task) = stack.pop() {
            match task {
                Task::Enter(i) => {
                    if visited[i] {
                        continue;
                    }
                    visited[i] = true;
                    stack.push(Task::Eval(i));
                    if i == self.focus.0 {
                        // For the replaced node, traverse the NEW node's children
                        new_node.children_into(&mut ch_buf);
                    } else {
                        self.src.nodes[i].children_into(&mut ch_buf);
                    }
                    for &c in ch_buf.iter().rev() {
                        if !visited[c] {
                            stack.push(Task::Enter(c));
                        }
                    }
                }
                Task::Eval(i) => {
                    if i == self.focus.0 {
                        let remapped = new_node.map_ref(|&c: &usize| mapping[c]);
                        mapping[i] = dst.push(remapped).0;
                    } else {
                        let remapped = self.src.nodes[i].map_ref(|&c: &usize| mapping[c]);
                        mapping[i] = dst.push(remapped).0;
                    }
                }
            }
        }
        (dst, Id(mapping[root.0]))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Clone, PartialEq, Eq, Hash, Debug)]
    enum E<R> {
        Lit(i64),
        Add(R, R),
        Mul(R, R),
        Neg(R),
    }

    impl<R> Functor<R> for E<R> {
        type Mapped<S> = E<S>;
        fn map<S>(self, mut f: impl FnMut(R) -> S) -> E<S> {
            match self {
                E::Lit(n) => E::Lit(n),
                E::Add(a, b) => E::Add(f(a), f(b)),
                E::Mul(a, b) => E::Mul(f(a), f(b)),
                E::Neg(a) => E::Neg(f(a)),
            }
        }
    }

    impl_no_variadic!(E<usize>);

    type Expr = Arena<E<usize>>;

    fn lit(a: &mut Expr, n: i64) -> Id {
        a.push(E::Lit(n))
    }
    fn add(a: &mut Expr, l: Id, r: Id) -> Id {
        a.push(E::Add(l.0, r.0))
    }
    fn mul(a: &mut Expr, l: Id, r: Id) -> Id {
        a.push(E::Mul(l.0, r.0))
    }
    fn neg(a: &mut Expr, x: Id) -> Id {
        a.push(E::Neg(x.0))
    }

    fn show(a: &Expr, root: Id) -> String {
        a.fold(root, |node: E<String>| match node {
            E::Lit(n) => n.to_string(),
            E::Add(a, b) => format!("({a} + {b})"),
            E::Mul(a, b) => format!("({a} * {b})"),
            E::Neg(a) => format!("(-{a})"),
        })
    }

    // (1 + 2) * (-(3))
    fn sample() -> (Expr, Id) {
        let mut e = Expr::new();
        let one = lit(&mut e, 1);
        let two = lit(&mut e, 2);
        let three = lit(&mut e, 3);
        let sum = add(&mut e, one, two);
        let n3 = neg(&mut e, three);
        let root = mul(&mut e, sum, n3);
        (e, root)
    }

    #[test]
    fn cata_eval() {
        let (e, root) = sample();
        let val = e.fold(root, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
            E::Neg(a) => -a,
        });
        assert_eq!(val, (1 + 2) * -3);
    }

    #[test]
    fn cata_size() {
        let (e, root) = sample();
        let size = e.fold(root, |node: E<usize>| match node {
            E::Lit(_) => 1,
            E::Add(a, b) | E::Mul(a, b) => 1 + a + b,
            E::Neg(a) => 1 + a,
        });
        assert_eq!(size, 6);
    }

    #[test]
    fn cata_show() {
        let (e, root) = sample();
        assert_eq!(show(&e, root), "((1 + 2) * (-3))");
    }

    #[test]
    fn para_subtree_ids() {
        let (e, root) = sample();
        // Para gives (Id, A) — the Id is the original subtree handle.
        // Use it to check that the root's direct children are accessible.
        let (left_id, right_id) = e.fold_with_ids(root, |node: E<(Id, (Id, Id))>| match node {
            E::Lit(_) => (Id(usize::MAX), Id(usize::MAX)),
            E::Add((lid, _), (rid, _)) | E::Mul((lid, _), (rid, _)) => (lid, rid),
            E::Neg((cid, _)) => (cid, cid),
        });
        // Root is Mul(Add(...), Neg(...)) — check we got valid, distinct ids
        assert_ne!(left_id, right_id);
        assert_eq!(show(&e, left_id), "(1 + 2)");
        assert_eq!(show(&e, right_id), "(-3)");
    }

    #[test]
    fn zygo_eval_and_annotate() {
        let (e, root) = sample();
        let result = e.fold_with_aux(
            root,
            |node: E<i64>| match node {
                E::Lit(n) => n,
                E::Add(a, b) => a + b,
                E::Mul(a, b) => a * b,
                E::Neg(a) => -a,
            },
            |node: E<(String, i64)>| match node {
                E::Lit(n) => format!("{n}"),
                E::Add((a, _), (b, _)) => format!("({a} + {b})"),
                E::Mul((a, _), (b, _)) => format!("({a} * {b})"),
                E::Neg((a, _)) => format!("(-{a})"),
            },
        );
        assert_eq!(result, "((1 + 2) * (-3))");
    }

    #[test]
    fn mutu_even_odd() {
        // Chain of 7 Add nodes as a unary encoding
        let mut e = Expr::new();
        let base = lit(&mut e, 0);
        let mut tip = base;
        for _ in 0..7 {
            let z = lit(&mut e, 0);
            tip = add(&mut e, tip, z);
        }
        let (is_even, is_odd) = e.fold_pair(
            tip,
            |node: E<(bool, bool)>| match node {
                E::Lit(_) => true,
                E::Add((_, odd), _) => odd,
                _ => false,
            },
            |node: E<(bool, bool)>| match node {
                E::Lit(_) => false,
                E::Add((even, _), _) => even,
                _ => false,
            },
        );
        assert!(!is_even);
        assert!(is_odd);
    }

    #[test]
    fn transform_rewrite() {
        let mut e = Expr::new();
        let five = lit(&mut e, 5);
        let zero = lit(&mut e, 0);
        let root = add(&mut e, five, zero);

        let (e2, r2) = e.transform(root, |node| match node {
            E::Add(a, b) if b == a => E::Mul(a, b),
            other => other,
        });
        // 5 != 0, so no rewrite
        assert_eq!(show(&e2, r2), "(5 + 0)");
    }

    #[test]
    fn fold_short_early_exit() {
        let (e, root) = sample();
        let has_neg = e.fold_short(root, |node: E<bool>| match node {
            E::Neg(_) => Err(true),
            E::Lit(_) => Ok(false),
            E::Add(a, b) | E::Mul(a, b) => Ok(a || b),
        });
        assert!(has_neg);
    }

    #[test]
    fn hash_consing_dedup() {
        let mut e: HcArena<E<usize>> = Arena::new_dedup();
        let a = e.push(E::Lit(1));
        let b = e.push(E::Lit(2));
        let sum1 = e.push(E::Add(a.0, b.0));
        let a2 = e.push(E::Lit(1));
        let b2 = e.push(E::Lit(2));
        let sum2 = e.push(E::Add(a2.0, b2.0));
        assert_eq!(sum1, sum2);
        assert_eq!(e.len(), 3); // Lit(1), Lit(2), Add — not 6
    }

    #[test]
    fn hc_arena_cata() {
        let (arena, root) = sample();
        let (hc, root) = Arena::from_arena(&arena, root);
        let val = hc.fold(root, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
            E::Neg(a) => -a,
        });
        assert_eq!(val, -9);
    }

    #[test]
    fn hc_arena_para() {
        let (arena, root) = sample();
        let (hc, root) = Arena::from_arena(&arena, root);
        let (l, r) = hc.fold_with_ids(root, |node: E<(Id, (Id, Id))>| match node {
            E::Lit(_) => (Id(usize::MAX), Id(usize::MAX)),
            E::Add((l, _), (r, _)) | E::Mul((l, _), (r, _)) => (l, r),
            E::Neg((c, _)) => (c, c),
        });
        assert_ne!(l, r);
    }

    #[test]
    fn hc_arena_transform() {
        let (arena, root) = sample();
        let (hc, root) = Arena::from_arena(&arena, root);
        let (hc2, root2) = hc.transform(root, |node| match node {
            E::Neg(inner) => E::Mul(inner, inner),
            other => other,
        });
        let val = hc2.fold(root2, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
            E::Neg(a) => -a,
        });
        // (1+2) * Neg(3) -> (1+2) * Mul(3,3) = 3 * 9 = 27
        assert_eq!(val, 27);
    }

    #[test]
    fn ana_hc_dedup() {
        // Unfold binary tree — HcArena should deduplicate shared subtrees
        let mut hc = Arena::new_dedup();
        let root = unfold_hc(&mut hc, 3u32, |n| {
            if n == 0 {
                (E::Lit(1), vec![])
            } else {
                (E::Add(0, 0), vec![n - 1, n - 1])
            }
        });
        // Full binary tree of depth 3 has 15 nodes, but with hash-consing
        // each level is shared: Lit(1), Add(Lit,Lit), Add(Add,Add), Add(Add2,Add2)
        assert!(hc.len() < 15);
        let val = hc.fold(root, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
            E::Neg(a) => -a,
        });
        assert_eq!(val, 8);
    }

    #[test]
    fn apo_hc_unfold() {
        let mut hc: HcArena<E<usize>> = Arena::new_dedup();
        let leaf = hc.push(E::Lit(42));
        let root = unfold_short_hc(&mut hc, 2i32, |n| {
            if n <= 1 {
                (E::Neg(0), vec![Seed::Done(leaf)])
            } else {
                (E::Neg(0), vec![Seed::Continue(n - 1)])
            }
        });
        let val = hc.fold(root, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Neg(a) => -a,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
        });
        assert_eq!(val, 42);
    }

    #[test]
    fn histo_depth() {
        let (e, root) = sample();
        let depth = e.fold_with_history(root, |node: E<&Ann<usize>>| match node {
            E::Lit(_) => 0,
            E::Add(a, b) | E::Mul(a, b) => 1 + a.value.max(b.value),
            E::Neg(a) => 1 + a.value,
        });
        assert_eq!(depth, 2);
    }

    #[test]
    fn prepro_normalize_then_fold() {
        let mut e = Expr::new();
        let five = lit(&mut e, 5);
        let n1 = neg(&mut e, five);
        let root = neg(&mut e, n1);

        let result = e.prefold(
            root,
            |node| match node {
                E::Neg(_) => E::Lit(0),
                other => other,
            },
            |node: E<i64>| match node {
                E::Lit(n) => n,
                E::Add(a, b) => a + b,
                E::Mul(a, b) => a * b,
                E::Neg(a) => -a,
            },
        );
        assert_eq!(result, 0);
    }

    #[test]
    fn transform_no_match() {
        let mut e = Expr::new();
        let five = lit(&mut e, 5);
        let zero = lit(&mut e, 0);
        let root = add(&mut e, five, zero);

        let (e2, r2) = e.transform(root, |node| match node {
            E::Add(a, b) if a == b => E::Mul(a, b),
            other => other,
        });
        assert_eq!(show(&e2, r2), "(5 + 0)");
    }

    #[test]
    fn fold_short_no_early_exit() {
        let mut e = Expr::new();
        let a = lit(&mut e, 1);
        let b = lit(&mut e, 2);
        let root = add(&mut e, a, b);
        let has_neg = e.fold_short(root, |node: E<bool>| match node {
            E::Neg(_) => Err(true),
            E::Lit(_) => Ok(false),
            E::Add(a, b) | E::Mul(a, b) => Ok(a || b),
        });
        assert!(!has_neg);
    }

    #[test]
    fn push_no_dedup() {
        let mut e = Expr::new();
        let _ = e.push(E::Lit(1));
        let _ = e.push(E::Lit(1));
        assert_eq!(e.len(), 2); // no dedup — both stored
    }

    #[test]
    fn arena_accessors() {
        let mut e = Expr::new();
        assert!(e.is_empty());
        let id = lit(&mut e, 42);
        assert!(!e.is_empty());
        assert_eq!(e.len(), 1);
        match e.get(id) {
            E::Lit(42) => {}
            _ => panic!("expected Lit(42)"),
        }
    }

    #[test]
    fn hc_arena_accessors() {
        let (arena, root) = sample();
        let (hc, _root) = Arena::from_arena(&arena, root);
        assert!(!hc.is_empty());
        assert!(!hc.is_empty());
        assert!(matches!(hc.get(Id(0)), E::Lit(_)));
    }

    #[test]
    fn histo_children_field() {
        let (e, root) = sample();
        let max_fanout = e.fold_with_history(root, |node: E<&Ann<usize>>| match node {
            E::Lit(_) => 0,
            E::Add(a, b) | E::Mul(a, b) => {
                let own = a.children.len().max(b.children.len());
                2usize.max(a.value.max(b.value)).max(own)
            }
            E::Neg(a) => 1usize.max(a.value),
        });
        assert!(max_fanout >= 2);
    }

    // -- Unfolds --

    #[test]
    fn ana_build_tree() {
        // Unfold: n -> Add(n-1, n-1) until n==0 -> Lit(1)
        let mut arena = Expr::new();
        let root = unfold(&mut arena, 3u32, |n| {
            if n == 0 {
                (E::Lit(1), vec![])
            } else {
                (E::Add(0, 0), vec![n - 1, n - 1])
            }
        });
        let val = arena.fold(root, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
            E::Neg(a) => -a,
        });
        assert_eq!(val, 8); // 2^3
    }

    #[test]
    fn ana_deep_chain_no_stack_overflow() {
        // A chain of 1_000_000 Neg nodes — would blow the stack if recursive
        let mut arena = Expr::new();
        let root = unfold(&mut arena, 1_000_000u32, |n| {
            if n == 0 {
                (E::Lit(42), vec![])
            } else {
                (E::Neg(0), vec![n - 1])
            }
        });
        // Even depth: 1_000_000 negations cancel out
        let val = arena.fold(root, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Neg(a) => -a,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
        });
        assert_eq!(val, 42);
    }

    #[test]
    fn apo_early_stop() {
        // Pre-populate arena with a leaf node, then unfold_short reuses it via Done
        let mut arena = Expr::new();
        let leaf = lit(&mut arena, 99);

        // Unfold: seed=2 -> Neg(Continue(1)) -> Neg(Done(leaf))
        let root = unfold_short(&mut arena, 2i32, |n| {
            if n <= 1 {
                (E::Neg(0), vec![Seed::Done(leaf)])
            } else {
                (E::Neg(0), vec![Seed::Continue(n - 1)])
            }
        });
        let val = arena.fold(root, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Neg(a) => -a,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
        });
        // Neg(Neg(Lit(99))) = 99
        assert_eq!(val, 99);
    }

    #[test]
    fn apo_unfold_chain() {
        // Build Neg(Neg(Neg(Lit(42)))) for depth=3, all Continue (no Done)
        let mut arena = Expr::new();
        let root = unfold_short(&mut arena, 3i32, |n| {
            if n == 0 {
                (E::Lit(42), vec![])
            } else {
                (E::Neg(0), vec![Seed::Continue(n - 1)])
            }
        });
        let val = arena.fold(root, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Neg(a) => -a,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
        });
        assert_eq!(val, -42); // 3 negations: -(-(-42)) = -42
    }

    #[test]
    fn postpro_normalize_during_unfold() {
        // Unfold chain of Negs, but post-normalize strips them to Lit(0)
        let mut arena = Expr::new();
        let root = postunfold(
            &mut arena,
            2u32,
            |node| match node {
                E::Neg(_) => E::Lit(0),
                other => other,
            },
            |n| {
                if n == 0 {
                    (E::Lit(1), vec![])
                } else {
                    (E::Neg(0), vec![n - 1])
                }
            },
        );
        let val = arena.fold(root, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Neg(a) => -a,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
        });
        // All Negs replaced with Lit(0) by post
        assert_eq!(val, 0);
    }

    // -- Refolds --

    #[test]
    fn hylo_factorial() {
        let result = refold(
            5u64,
            &|n| {
                if n == 0 {
                    (1u64, vec![])
                } else {
                    (n, vec![n - 1])
                }
            },
            &|n, children: Vec<u64>| {
                if children.is_empty() {
                    n
                } else {
                    n * children[0]
                }
            },
        );
        assert_eq!(result, 120);
    }

    #[test]
    fn dyna_with_history() {
        // Build a chain via unfold, fold with history to compute depth
        let result = refold_with_history(
            4u32,
            |n| {
                if n == 0 {
                    (E::Lit(0), vec![])
                } else {
                    (E::Neg(0), vec![n - 1])
                }
            },
            |node: E<&Ann<usize>>| match node {
                E::Lit(_) => 0,
                E::Neg(a) => 1 + a.value,
                E::Add(a, b) | E::Mul(a, b) => 1 + a.value.max(b.value),
            },
        );
        assert_eq!(result, 4);
    }

    #[test]
    fn chrono_same_as_dyna() {
        let result = refold_full(
            3u32,
            |n| {
                if n == 0 {
                    (E::Lit(1), vec![])
                } else {
                    (E::Add(0, 0), vec![n - 1, n - 1])
                }
            },
            |node: E<&Ann<i64>>| match node {
                E::Lit(n) => n,
                E::Add(a, b) => a.value + b.value,
                E::Mul(a, b) => a.value * b.value,
                E::Neg(a) => -a.value,
            },
        );
        assert_eq!(result, 8);
    }

    // -- Additional Arena schemes --

    #[test]
    fn fold_with_original_sees_node() {
        let (e, root) = sample();
        // fold_with_original: count nodes, but double-count Neg nodes
        let count = e.fold_with_original(root, |orig: &E<usize>, node: E<usize>| {
            let base = match node {
                E::Lit(_) => 1,
                E::Add(a, b) | E::Mul(a, b) => 1 + a + b,
                E::Neg(a) => 1 + a,
            };
            match orig {
                E::Neg(_) => base + 1, // extra count for Neg
                _ => base,
            }
        });
        // Normal size is 6, one Neg node adds 1 extra
        assert_eq!(count, 7);
    }

    #[test]
    fn transform_down_pre_order() {
        // Build Neg(Neg(Lit(5)))
        let mut e = Expr::new();
        let five = lit(&mut e, 5);
        let n1 = neg(&mut e, five);
        let root = neg(&mut e, n1);

        // transform_down: replace Neg(x) with Mul(x, x) pre-order
        let (e2, r2) = e.rewrite_down(root, |node| match node {
            E::Neg(inner) => E::Mul(inner, inner),
            other => other,
        });
        // Pre-order: outer Neg(Neg(Lit(5))) -> Mul(Neg(Lit(5)), Neg(Lit(5)))
        // Then inner Negs also rewritten -> Mul(Mul(Lit(5),Lit(5)), Mul(Lit(5),Lit(5)))
        let val = e2.fold(r2, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Neg(a) => -a,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
        });
        assert_eq!(val, 625); // 5^4
    }

    // -- HcArena: fold_mut, prefold, rewrite, rewrite_down --

    fn hc_sample() -> (HcArena<E<usize>>, Id) {
        let (arena, root) = sample();
        Arena::from_arena(&arena, root)
    }

    #[test]
    fn hc_fold_mut_count_nodes() {
        let (hc, root) = hc_sample();
        let mut count = 0usize;
        let val = hc.fold_mut(root, &mut count, |node: E<i64>, st: &mut usize| {
            *st += 1;
            match node {
                E::Lit(n) => n,
                E::Add(a, b) => a + b,
                E::Mul(a, b) => a * b,
                E::Neg(a) => -a,
            }
        });
        assert_eq!(val, -9);
        assert_eq!(count, 6);
    }

    #[test]
    fn hc_prefold_normalize_then_fold() {
        let mut e = Expr::new();
        let five = lit(&mut e, 5);
        let n1 = neg(&mut e, five);
        let root = neg(&mut e, n1);
        let (hc, root) = Arena::from_arena(&e, root);

        let result = hc.prefold(
            root,
            |node| match node {
                E::Neg(_) => E::Lit(0),
                other => other,
            },
            |node: E<i64>| match node {
                E::Lit(n) => n,
                E::Add(a, b) => a + b,
                E::Mul(a, b) => a * b,
                E::Neg(a) => -a,
            },
        );
        assert_eq!(result, 0);
    }

    #[test]
    fn hc_rewrite_full_power() {
        let (hc, root) = hc_sample();
        // Replace Neg(x) with Mul(x, x) using rewrite (can create new nodes)
        let (hc2, root2) = hc.rewrite(root, |node, arena| match node {
            E::Neg(inner) => arena.push(E::Mul(inner, inner)),
            other => arena.push(other),
        });
        let val = hc2.fold(root2, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
            E::Neg(a) => -a,
        });
        // (1+2) * (3*3) = 3 * 9 = 27
        assert_eq!(val, 27);
    }

    #[test]
    fn hc_rewrite_down_pre_order() {
        let mut e = Expr::new();
        let five = lit(&mut e, 5);
        let n1 = neg(&mut e, five);
        let root = neg(&mut e, n1);
        let (hc, root) = Arena::from_arena(&e, root);

        let (hc2, root2) = hc.rewrite_down(root, |node| match node {
            E::Neg(inner) => E::Mul(inner, inner),
            other => other,
        });
        let val = hc2.fold(root2, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Neg(a) => -a,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
        });
        assert_eq!(val, 625); // 5^4
    }

    // -- Sparse memoization strategy --

    #[test]
    fn sparse_fold_matches_dense() {
        let (e, root) = sample();
        let dense = e.fold(root, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
            E::Neg(a) => -a,
        });
        let sparse = e
            .with_strategy::<Sparse>()
            .fold(root, |node: E<i64>| match node {
                E::Lit(n) => n,
                E::Add(a, b) => a + b,
                E::Mul(a, b) => a * b,
                E::Neg(a) => -a,
            });
        assert_eq!(dense, sparse);
    }

    #[test]
    fn sparse_small_subtree_in_large_arena() {
        // Build a large arena, then fold only a small subtree with Sparse
        let mut e = Expr::new();
        // Push 1000 unrelated nodes
        for i in 0..1000 {
            lit(&mut e, i);
        }
        // Now build a small tree
        let a = lit(&mut e, 10);
        let b = lit(&mut e, 20);
        let root = add(&mut e, a, b);
        assert!(e.len() > 1000);
        let val = e
            .with_strategy::<Sparse>()
            .fold(root, |node: E<i64>| match node {
                E::Lit(n) => n,
                E::Add(a, b) => a + b,
                E::Mul(a, b) => a * b,
                E::Neg(a) => -a,
            });
        assert_eq!(val, 30);
    }

    #[test]
    fn sparse_transform() {
        let (e, root) = sample();
        let (e2, r2) = e
            .with_strategy::<Sparse>()
            .transform(root, |node| match node {
                E::Neg(inner) => E::Mul(inner, inner),
                other => other,
            });
        let val = e2.fold(r2, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
            E::Neg(a) => -a,
        });
        assert_eq!(val, 27);
    }

    #[test]
    fn sparse_rewrite_down() {
        let mut e = Expr::new();
        let five = lit(&mut e, 5);
        let n1 = neg(&mut e, five);
        let root = neg(&mut e, n1);
        let (e2, r2) = e
            .with_strategy::<Sparse>()
            .rewrite_down(root, |node| match node {
                E::Neg(inner) => E::Mul(inner, inner),
                other => other,
            });
        let val = e2.fold(r2, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Neg(a) => -a,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
        });
        assert_eq!(val, 625);
    }

    // -- Zipper --

    #[test]
    fn zipper_navigate_down_up() {
        let (e, root) = sample(); // (1 + 2) * (-(3))
        let mut z = Zipper::new(&e, root);
        assert_eq!(z.depth(), 0);
        assert!(z.down(0)); // left child: (1 + 2)
        assert_eq!(z.depth(), 1);
        assert!(z.down(0)); // left-left: 1
        assert_eq!(z.depth(), 2);
        assert!(matches!(z.focus(), E::Lit(1)));
        assert!(z.up());
        assert!(matches!(z.focus(), E::Add(_, _)));
        assert!(z.up());
        assert!(matches!(z.focus(), E::Mul(_, _)));
        assert!(!z.up()); // already at root
    }

    #[test]
    fn zipper_sibling() {
        let (e, root) = sample();
        let mut z = Zipper::new(&e, root);
        z.down(0); // Add(1, 2)
        z.down(0); // Lit(1)
        assert!(matches!(z.focus(), E::Lit(1)));
        assert!(z.sibling(1)); // Lit(2)
        assert!(matches!(z.focus(), E::Lit(2)));
    }

    #[test]
    fn zipper_child_count() {
        let (e, root) = sample();
        let z = Zipper::new(&e, root);
        assert_eq!(z.child_count(), 2); // Mul has 2 children
    }

    #[test]
    fn zipper_down_out_of_bounds() {
        let (e, root) = sample();
        let mut z = Zipper::new(&e, root);
        assert!(!z.down(5)); // Mul only has 2 children
        assert_eq!(z.depth(), 0); // didn't move
    }

    #[test]
    fn zipper_top() {
        let (e, root) = sample();
        let mut z = Zipper::new(&e, root);
        z.down(0);
        z.down(1);
        assert_eq!(z.depth(), 2);
        z.top();
        assert_eq!(z.depth(), 0);
        assert_eq!(z.focus_id(), root);
    }

    #[test]
    fn zipper_path() {
        let (e, root) = sample();
        let mut z = Zipper::new(&e, root);
        z.down(1); // Neg
        z.down(0); // Lit(3)
        let path = z.path();
        assert_eq!(path.len(), 2);
        assert_eq!(path[0].node_id, root);
        assert_eq!(path[0].child_index, 1);
        assert_eq!(path[1].child_index, 0);
    }

    #[test]
    fn zipper_mut_set_focus() {
        let mut e = Expr::new();
        let one = lit(&mut e, 1);
        let two = lit(&mut e, 2);
        let root = add(&mut e, one, two);

        let mut z = ZipperMut::new(&mut e, root);
        z.down(0); // Lit(1)
        z.set_focus(E::Lit(99));
        z.top();

        let val = e.fold(root, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
            E::Neg(a) => -a,
        });
        assert_eq!(val, 101); // 99 + 2
    }

    #[test]
    fn zipper_edit_cow() {
        let mut e = Expr::new();
        let one = lit(&mut e, 1);
        let two = lit(&mut e, 2);
        let three = lit(&mut e, 3);
        let sum = add(&mut e, one, two);
        let n3 = neg(&mut e, three);
        let root = mul(&mut e, sum, n3);

        let mut z = ZipperCow::new(&e, root);
        z.down(0); // focus on Add(1, 2)

        // Replace Add(1,2) with Lit(42) — just pass the node directly
        let (e2, r2) = z.set_focus(E::Lit(42));
        let val = e2.fold(r2, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
            E::Neg(a) => -a,
        });
        // Mul(Lit(42), Neg(Lit(3))) = 42 * (-3) = -126
        assert_eq!(val, -126);

        // Original arena is untouched
        let orig_val = e.fold(root, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Add(a, b) => a + b,
            E::Mul(a, b) => a * b,
            E::Neg(a) => -a,
        });
        assert_eq!(orig_val, -9);
    }

    #[test]
    fn zipper_cow_at_root() {
        let mut e = Expr::new();
        let _one = lit(&mut e, 1);
        let z = ZipperCow::new(&e, _one);
        let (e2, r2) = z.set_focus(E::Lit(99));
        let val = e2.fold(r2, |node: E<i64>| match node {
            E::Lit(n) => n,
            _ => 0,
        });
        assert_eq!(val, 99);
    }

    #[test]
    fn zipper_cow_mutate_focused_value() {
        // The real use case: read the focused node, compute a new value, set it
        let mut e = Expr::new();
        let five = lit(&mut e, 5);
        let three = lit(&mut e, 3);
        let root = add(&mut e, five, three);

        let mut z = ZipperCow::new(&e, root);
        z.down(0); // focus on Lit(5)

        // Read the value, double it
        let &E::Lit(n) = z.focus() else {
            panic!("expected Lit")
        };
        let (e2, r2) = z.set_focus(E::Lit(n * 2));
        let val = e2.fold(r2, |node: E<i64>| match node {
            E::Lit(n) => n,
            E::Add(a, b) => a + b,
            _ => 0,
        });
        assert_eq!(val, 13); // 10 + 3
    }
}
