name: Publish
on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-rust
      - run: cargo test --workspace --exclude semi-persistent-abstract-domains
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo publish -p semi-persistent-containers
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - run: cargo publish -p semi-persistent
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - run: cargo publish -p semi-persistent-traversals-derive
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - run: cargo publish -p semi-persistent-traversals
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - run: cargo publish -p semi-persistent-egraph
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
